### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by drramki-chop** [brentp/mosdepth#10]
the compiled binary throws an error in a centOS environment....

**Comment by brentp** [comment]
yeah. this means you'll have to either build yourself, following the .travis.yml, or get the binary from bioconda, which uses an older GLIBC to build. 
in the next release, I might try to grab just the bioconda build or builder, but for now, you'll have to get it yourself.

**Comment by brentp** [comment]
I updated the binaries here: https://github.com/brentp/mosdepth/releases/tag/v0.1.7
with one pulled from bioconda. Would you give it a try?

**Comment by drramki-chop** [comment]
Thanks for the response. I tried the conda package later. I guess the binary works but now throws an htslib.so error. I tried setting the LD_LIBRARY_PATH env variable but continues to complain. I'll look into it more closely tomorrow and update here. Thanks again~!

**Comment by brentp** [comment]
can you type ls -lh $LD_LIBRARY_PATH and report the result?

**Comment by drramki-chop** [comment]
the LD_LIBRARY_PATH worked. However, now its throwing error about older pcre version. https://github.com/docopt/docopt.nim/issues/13

Perhaps, Docker kind of solution is what will work! Let me know if think there is another way...

**Comment by brentp** [comment]
yeah. bioconda has docker builds for every project, so that would be the next thing to try. You could also build your own PCRE or ask the sysadmins to update.

**Comment by drramki-chop** [comment]
Thanks!

**Comment by brentp** [comment]
I'll leave this open. Maybe I can figure out how to get a static build as it would be good if this were extremely easy to install.

**Comment by dmckean** [comment]
I ran into this also on CentOS 6.9. Couldn't use the binary b/c glibc is too old (#19). Built my own PCRE locally and compiled with `nimble build --passL:-Wl,-rpath,/usr/local/lib -d:release` , also worked for the local htslib installs.

No idea if `nimble install` or `mosdepth.nimble` can be modified to alter the shared library path. I suppose `LD_LIBRARY_PATH` should work for PCRE as well.
