### ISSUE TITLE
Fragment coverage for pair-end data?

### ISSUE THREAD

**Issue by shenscore** [brentp/mosdepth#100]
Hi,
  could this tool be used to calculate the fragment coverage like below?

read1
-------------->****************************    
**************************<----------------  read2
  
1111111111111111111111111111111111

**Comment by brentp** [comment]
hi,
this is not currently possible with `mosdepth`. you could build your own version using [genoiser](https://github.com/brentp/genoiser) but it's not easily added to mosdepth.
