### ISSUE TITLE
mosdepth requires htslib<1.10?

### ISSUE THREAD

**Issue by finswimmer** [brentp/mosdepth#101]
Hello,

the bioconda recipe has a very strict requirement about the `hstlib` version:

```
htslib >=1.9,<1.10.0a0
```

`htslib` version 1.10 is out. Does it really won't work with `mosdepth` or needs the recipe a adoption?

fin swimmer

**Comment by brentp** [comment]
i'll make a release of hts-nim and mosdepth this month that work on htslib >=1.10

**Comment by brentp** [comment]
I tagged a new release that uses htslib 1.10: https://github.com/brentp/mosdepth/releases/tag/v0.2.7

**Comment by finswimmer** [comment]
Thanks a lot :+1:
