### ISSUE TITLE
mosdepth no binning?

### ISSUE THREAD

**Issue by aderzelle** [brentp/mosdepth#102]
Hello, I am running mosdepth in a very simple way, 

`mosdepth explosion.mosdepth -t 4 assemblyONT40kb.sorted.bam`

The problem is that the per base output has only
64253599 entries (genome size of 100 Mb). I understand mosdepth is binning together adjacent bases with same coverage. Is there a built-in way to get one line per base in the output, irrespective of the value of the neighbouring base?

thank you

**Comment by brentp** [comment]
hi, you can use either of the solutions here: https://github.com/brentp/mosdepth/issues/55

**Comment by aderzelle** [comment]
thanks! 
We have been several to have been a little confused about thtat, so may I suggest you write in the doc that the "per base" is also actually performing binning? 

Otherwise mosdepth is such a relief compared to other tools for its speed, I have used it instead of samtools everywhere.

**Comment by brentp** [comment]
i am happy to review a pull request with your suggested clarification. since it *is* per-base coverage info, it seems appropriate to me to call it such.

**Comment by aderzelle** [comment]
Indeed, I think it might be because we are coming from samtools and we wrongly translated "per base" with "ah okay, this is the samtools-like output format".
