### ISSUE TITLE
regions.dist.txt = global.dist.txt  when running mosdepth -n -b 10000 -t 4 -F 2816 

### ISSUE THREAD

**Issue by bwlang** [brentp/mosdepth#105]
I think i understand from another closed issue (#18) that you expect that global.dist.txt will always be "per base", but why make 2 identical files?  Perhaps when passing a bed file to limit to certain regions this makes more sense...

Am I missing something here?

**Comment by brentp** [comment]
perhaps you have a stale regions file in there from a previous run?
https://github.com/brentp/mosdepth/blob/master/mosdepth.nim#L595

**Comment by bwlang** [comment]
I don't think I have a stale file hanging around... I'm running this in a nextflow workflow (a work directory is created for each invocation with inputs symlinked in).
Sounds like they are not supposed to be identical. I can try reproduce on your test files if that's helpful.

**Comment by brentp** [comment]
please
