### ISSUE TITLE
The index file is older than the data file:

### ISSUE THREAD

**Issue by Biojenifer** [brentp/mosdepth#109]
Hi,

do you know why the program is giving me this warning? And do you know if it is something dangerous? The program seems to work properly.

The error is the following: [W::hts_idx_load2] The index file is older than the data file:

Thanks

**Comment by brentp** [comment]
if you copied your index and bam/cram at the same time, but the indexed finished first, it will have a modified time that is older than the bam. This message is from htslib telling you that the index is older as it can be a problem if the index is stale--if it was made from a previous version of the bam.
you can `touch` the index if you're sure it's correct, or just re-index the alignment file.
