### ISSUE TITLE
No summary.txt output

### ISSUE THREAD

**Issue by xiaoyunguo** [brentp/mosdepth#110]
Hi, 
I used mosdepth to calculate coverage, all seems to go well except there is no xxx.summary.txt file output. There is not error message either. I wonder why. 

Thanks

Xiaoyun

**Comment by brentp** [comment]
what does:
```
mosdepth --version
```
show? The summary was added in version 0.2.6

**Comment by xiaoyunguo** [comment]
Thank you so much for the prompt reply. Yes, you got it right. mine is
0.2.5, time to update!

Best,

Xiaoyun

**Comment by xiaoyunguo** [comment]
I tried to update it through conda bio, but still version 0.2.5. Any clue?

Best,

Xiaoyun

**Comment by brentp** [comment]
all recent versions are available in bioconda
https://bioconda.github.io/recipes/mosdepth/README.html
