### ISSUE TITLE
*regions.bed.gz mean-depths don't match *.per-base.bed.gz

### ISSUE THREAD

**Issue by AlijahArcher** [brentp/mosdepth#113]
I've been loving the speed of execution with `mosdepth`, but am I missing something with the way mean depth is calculated in the `*regions.bed.gz` file?

my `mosdepth` call:
```
mosdepth -b my.bed -Q 1 -t 4 my_prefix my.bam
```

For example, looking at this region (from the `*regions.bed.gz` file):
```
chr1    861311  861403  473_403203_148398(SAMD11)_3     574.82
```

If I try to find the number of bases in this region, (I don't get a whole number, but this is due to precision, I recognize) :
` (861403 - 861311) * 574.82 = 52883.44`

But, when I check this region in the *.per-base.bed.gz file, from adding up the total bases in this region I get:
```
awk '{sum += ($3 - $2) * $4;} END {print sum}' region_1.bed
> 53499
```
Which has a mean depth of 581.510869565 (53499 / 92)

Shouldn't these values match?  Is there more to the mean-depth calculation in the *regions.bed.gz file?  I couldn't find anything that would indicate so in the mosdepth paper or documentation.

**Comment by gabeng** [comment]
Have you taken into account that BED files are 0-based half open?
http://genome.ucsc.edu/blog/the-ucsc-genome-browser-coordinate-counting-systems/

**Comment by AlijahArcher** [comment]
Indeed

**Comment by AlijahArcher** [comment]
Oh, for whatever reason, I have a duplicated line in my intersected region file.  A fresh bedtools intersect fixed it.  Carry on, awesome tool.
