### ISSUE TITLE
N region?

### ISSUE THREAD

**Issue by wskwxf** [brentp/mosdepth#114]
Hi, I found depth and coverage contain N region,why use reference?
chr1    0       10001   1       0.01
for hg19,chr1:0-1000 is N. average depth= total depth/region size .The region size contains n, so I think it's incorrect to calculate the depth。

**Comment by brentp** [comment]
can you show the output of `samtools view $bam chr1:1-10000` for the bam in question?

**Comment by wskwxf** [comment]
> can you show the output of `samtools view $bam chr1:1-10000` for the bam in question?
my reference is hg19
E100001798L1C004R0250660061	129	chr1	9999	0	63S81M	chrY	59363140	0	CACTATGGTGACTAACCAGAAATGGGCATTCTGTAAATGCTAGATACAAAATAAATAAATAAGGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCT	EEEEEEEEEDEEEEFEEEEFEEEEDEEEFDEEEEEFEEEEEEEFEEEEEEFEDFEEEFEBEEEEFEEEEEDFEEEEDEEEECEEFEEEEEEEEEEEFEEEEEEEEEEEEEEEEEEEECEEEEEEEEEEEDEEEEE=EEEEE7EE	NM:i:0	MD:Z:81	MC:Z:144M	AS:i:81	XS:i:79	RG:Z:NA12878bgi	SA:Z:chr13,26286178,-,79S65M,0,0;
E100001798L1C004R0302388074	65	chr1	9999	0	55S66M23S	chr6	93812543	0	ATATCCCCCAAGTATGAGTTGCCTAGAACAGCTCTTCCTTTATTTTCTTTTTCTGGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACAGAGATAACTATTGATACAACAC	E=E9EDCCEEC==EEDA8BEEEDEEEBEEE@EEEEBCCE6EEEEEEEEDEEDEECD?CD>AEEEDCBDDEECDDEEEDEEEEDDCEE<E@DC@D4EDEEED>CDDD>BDEEEDBEEEEEDEE@DB=DDEEDDDDEABD>@EDD9	NM:i:0	MD:Z:66	MC:Z:138M	AS:i:66	XS:i:65	RG:Z:NA12878bgi	SA:Z:chr5,18606943,-,80S64M,0,0;
E100001798L1C030R0022748976	129	chr1	9999	0	50S94M	chrX	155260132	0	ACTCAGGCCTCTCTCCCTCTTGTCATGAAGCCACCCAGCCCCACTCCTATGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	EEEEEE9CEDDEEEEEEEEEEEEEEEEEEAEEEEDEEBEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDEEEEEEEEEEEDEEEEEBEEEEEEEEEDEECEEEEEEDEEEDBCEEEDEDDE@DEEEEBDCEE	NM:i:0	MD:Z:94	MC:Z:144M	AS:i:94	XS:i:92	RG:Z:NA12878bgi	SA:Z:chr13,93649045,-,86S58M,0,0;
E100001798L1C030R0022748977	129	chr1	9999	0	50S94M	chrX	155260132	0	ACTCAGGCCTCTCTCCCTCTTGTCATGAAGCCACCCAGCCCCACTCCTATGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	EEEEFE?EEEEEEEEEEEEEEE@EEEEEE@EEEEEEEDEDEEEEEEEFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEFEEEEEEEEEEEECEEEEEDEEEEEDEEEEEEEEEDEEEEEEEEECEEDEEECBEEDEEEE	NM:i:0	MD:Z:94	MC:Z:144M	AS:i:94	XS:i:92	RG:Z:NA12878bgi	SA:Z:chr13,93649045,-,86S58M,0,0;
E100001798L1C002R0360190636	177	chr1	9999	0	78S54M	chr3	196625626	0	ACAGACCGGAATGGAATCCACACCGAATGGAATCGAATGGTATCAACACCAACCGGAAAAAAACGGAATTATCGAATGGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	@.DB?&-)/&?2E2;E%8(6D8'>&.EEB:C@+E.C=DA<2E5AE'7BEAE8,CEECECE;@EEEE:>ED@5C2BEDE<CCBDDEE@@/E@<EB=<D9E7AEEEB;EDBDE4CDEE?BEC+C@E?DEEE<DE	NM:i:0	MD:Z:54	MC:Z:144M	AS:i:54	XS:i:52	RG:Z:NA12878bgi
E100001798L1C010R0101530106	177	chr1	9999	0	62S82M	chr4	39901775	0	ATAATTAGAATTAAATTTTGAGATAAAATTACATTAAACATCATATTTCTTTTTCACTGCATGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	DDDB?ED<EDBAEEAECDE@ECEEEEDDEE?DDEDED;DCEE9E6DDEEE?;E@;BEAB:CEEEEC-9?EEDBC8CEA?EBDEEED;EEDDB5EEDDBBDEDE@@DEDEEDCEEEC?CEEE;DCFEEDDEEEDECEECDDBEEE	NM:i:0	MD:Z:82	MC:Z:144M	AS:i:82	XS:i:80	RG:Z:NA12878bgi	SA:Z:chr4,39901713,+,79S65M,0,0;
E100001798L1C020R0281503335	113	chr1	9999	0	40S66M38S	chr5	18606943	0	GAGTTGCCTAGACCAGCTCTTCCTTTATTTTCTTTTTCTGGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACAGAGATAACTATTGATACAACACCTTCATGACCCTAAG	;E)@CE%ECAE@'E3@:-DDC;DDEE4CE?=@CCC:>8D=E?EBCCD?EB;E+DD3DDEEE=,;?EDDD2C@ED@CBDD@C7A<DA>@EEEDD5=EEBCECBEEDDEEEBEEE@DEEEEEEECE<AEDC@EBDEEEECD?EEEE	NM:i:0	MD:Z:66	MC:Z:34S110M	AS:i:66	XS:i:65	RG:Z:NA12878bgi	SA:Z:chr5,18606943,+,95S49M,0,1;chr5,18606896,+,40M104S,0,0;
E100001798L1C003R0210035048	161	chr1	10000	0	68S76M	chr5	10005	0	AACAAATTTGAAAACTTAGATGAAATGAACAAATTCCTTGAAAGACACATAATACCAAAGCTCACACAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA	EEEAFCEFEEEEEFEFEBEEEEDEEEEEEFEEEDFDFFFEEFEEFEDFEEEEEEEEEEEEEEFEEEFEEEEEFEEEEFEEEFEEFEEEEEEFFFEEEEEEEFFEFEEEFEEEEEEEFFEEEEEEEEEFEEEEFEEEEEFEEEEC	NM:i:0	MD:Z:76	MC:Z:144M	AS:i:76	XS:i:75	RG:Z:NA12878bgi	SA:Z:chr3,137998590,-,75S69M,0,0;
E100001798L1C005R0040703221	163	chr1	10000	44	8M1D47M1D89M	=	10053	197	CTAACCCTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	EEEEEDEEEEEE8EEEEEFEDAEDEDEEEEEEE@CDEEEEEEEEEEEEEEEEAEEE8EEEE?@EEEDEEEEEE?F>EEEED<EDEEE9E@EECEEEEDDEEAABCFECEBEDEE@DEDEE?C9DEDEECC>DDBEEEEEEEEEA	NM:i:3	MD:Z:0A7^A47^A89	MC:Z:3M1D121M1I19M	AS:i:129	XS:i:121	RG:Z:NA12878bgi	XA:Z:chr4,-191044073,21M3D16M1D98M1D9M,5;chr1,-249240087,13M1I19M4I12M1D95M,6;chr4,+10059,8M1D97M1D32M7S,4;chr18,+10040,8M1D29M1I69M2D11M1D26M,5;chr15,-102521204,2S12M1D6M1D6M1D11M1D98M1D9M,5;
E100001798L1C011R0220896181	129	chr1	10000	0	41S103M	chr12	133841747	0	TTGGGGGGTTGGGGGCTGGGGGAGGGNTAGCATTAGGAGAAATAANCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCNTAACCC	EAEEEEEEEEEEEEEEEEEEEEEEDE!DEDEEEEEEDEEEEEEEE!EEEEEEEEEEEEEEEEDEDEDEEEDEEEEEEEEEEDEEEEEEEEEEEDEEDEEEEEEEEDEEEEEEAEEEDEAEEEDDEECECDEDEEBEE!6DEEEE	NM:i:2	MD:Z:4C91C6	MC:Z:144M	AS:i:99	XS:i:98	RG:Z:NA12878bgi	SA:Z:chr3,158703507,-,99S45M,0,1;
E100001798L1C014R0122786484	129	chr1	10000	0	54S90M	chr12	133841650	0	GGCCTTTCATGAGAGGGGGATTGGTTTCATGACTCTCAATTTTGGAAGAATAGAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	FEDEFFEECEE<EDFEEEFEEEEEEEEE@EEEEDEFEEDDEFFDEE8EE>ECEEDEEEFEEEEDDEEEDFDEEEEEDEEEAEEEEEEEEEEEEEEEEEDEEEEEDEEEECEEEEDEEEEEEDEEDEDEEEEEEDDEDEEEDEED	NM:i:0	MD:Z:90	MC:Z:119M25S	AS:i:90	XS:i:89	RG:Z:NA12878bgi	SA:Z:chr6,90069548,+,62M82S,0,0;
E100001798L1C014R0161139420	129	chr1	10000	0	64S80M	chrX	155260133	0	GCGCTTAGCAACACTTAACATTAGAAAGCTCTGTCTCTGTGTGTCCCTAGCTTTTAAATGGGTAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCT	:??@EEE1CEE7E6DEEEDEC>EDEEED@E?EECCDDE@B;EDEA8BEE=@EEEDEEEEE8DDEEEEE?=CDEEC8CEED4CCEEE3C8EEEDBCEECD@BEEEEBBDED?DBEECB>@EBEDDEEE@*@1DDC;<<DE7C=CC	NM:i:0	MD:Z:80	MC:Z:144M	AS:i:80	XS:i:79	RG:Z:NA12878bgi	SA:Z:chr2,217192307,+,70M74S,0,0;
E100001798L1C037R0173130374	161	chr1	10000	9	8M1D59M1D77M	chr5	11715	0	CTAACCCTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCAACCCTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	EED=EDEFAEEDEDCEE:ECCEEEEDEEEEEEEEEDEDEEEEE@?EECDDEEEECEDEEEECAEEE?<EEE=EEEEEC4EEEE@8EDEEE@AEEE@?@EEF::DEEEB=DFECCEEEEAEBEEE?CCEDE7DEEEE8BCEEE>E	NM:i:4	MD:Z:0A7^A52T6^A77	MC:Z:9M1D80M55S	AS:i:124	XS:i:118	RG:Z:NA12878bgi	XA:Z:chr5,+11633,8M1D59M1D40M1D37M,4;chr15,-102521231,14S23M1D98M1D9M,4;chr1,-249240093,7M1I18M1D11M2D86M1I11M1D9M,7;
E100001798L1C040R0231695919	161	chr1	10000	0	53S91M	chr5	10031	0	CTTTTTCTTCCTTGCCCAAATTCTTATCTAAGGGGCCTAGGGAGTTATGCTCTATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCC	8EEEEFBEECEE@;DEBEEEFEEEE>D>E9E'@-1E@FE,+?E9EEEE=EEEFECECDEBEDDEBAFCEEDEEEECEEEEEEEDDEDEEEEEEEEEDBEEEDEEEEEEEEEEEDFEEDEEEE?EEEEEEFEEEEEFFE@CEEEE	NM:i:0	MD:Z:91	MC:Z:25S119M	AS:i:91	XS:i:90	RG:Z:NA12878bgi	SA:Z:chrX,1745532,-,86S58M,0,0;
E100001798L1C006R0133394652	177	chr1	10000	0	40S104M	chr16	21574411	0	CAGTTATGAAGGCTGGGAAGTCTGAGATCAGGGTGCCAGCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCT	CDE?A>CCEE=7E<D0ACE<EDBBE<?EEE?E;EC.>EBD.ECBBEEE;@=D>EEDEDECB3B2EE7=@=EEE?EDEEE.D=DECBDEEEA9/<EDE4E2EECB@=DFC>3?DEAE9?5EBEE?=E<E4C;EDCCCEED4CADE	NM:i:0	MD:Z:104	MC:Z:144M	AS:i:104	XS:i:103	RG:Z:NA12878bgi	SA:Z:chr16,21574374,+,102S42M,0,0;
E100001798L1C011R0253875369	113	chr1	10000	0	42S102M	chr4	169634121	0	AGAGAGAAAAGAGTAGGCTAGTCAATGCTAGGGAAATAAAGAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	EEEEEDEEEEEEEEEEEEDEE;EDEEEDEEDAAEEDA<EEEEEEEDEECEEDEDEEDDDEEEECEEEEECEEEEEEEEEEECEEEEEEEEEEBCEEEEEDEEDDDEEEEECEDEEEEDEEEEEEDEAEEEEEEEEECCEEAEBE	NM:i:0	MD:Z:102	MC:Z:144M	AS:i:102	XS:i:101	RG:Z:NA12878bgi	SA:Z:chr4,169633988,+,95S49M,0,0;
E100001798L1C011R0352187011	145	chr1	10000	0	52S92M	=	91243122	91233032	ATTTCTGCTGAGTGTCTCCAAGATGCCTCAGACATCTCTGGGTACTTTTTGCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCT	:C;EDCDDAEECEE<E<CEEEDAE?@EDAED?E<EEEEECEEECEEEE=ECEECEDEDEEBEEEEE?>EDEEDAEEEECDEEDEDCEEEEEDECEEEBEBEEECDEEEA?EEEECDEDEEDDDDEEEDDDEFEEEDEEDEEDEE	NM:i:0	MD:Z:92	MC:Z:144M	AS:i:92	XS:i:91	RG:Z:NA12878bgi	SA:Z:chr1,91243219,-,53M91S,0,0;
E100001798L1C015R0150427817	177	chr1	10000	0	61S83M	chr5	103920743	0	AAGCAGCTGCCTTGATCCACTCTAGAAAAATGTTCAGAGTCTATGTTTCCTGTTGACACCCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	EEDED>ADEEEDE@E9EEDEEEEEDEEEE>ECDEEE=EEEEEEEEEEEDEFEEECAECEBEEEEEEDEECEEEEEECAEEFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEBEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	NM:i:0	MD:Z:83	MC:Z:58S86M	AS:i:83	XS:i:82	RG:Z:NA12878bgi	SA:Z:chr5,103920743,+,80S64M,0,0;
E100001798L1C018R0293069090	81	chr1	10000	0	36S108M	=	49680058	49669952	TTTTACACACCATCTGCTGGTAGACTGAGACTAGTAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	DEEEBEEEEDEDDDEE=DDEDEDDEEEE<BDEEDEEEE@EBCECEDEDDEDD=ECCDEAECEECEDCEEEEEEE8EEADEEEC<DEEDDE?EEED?EEEECDEEEEDDEEEEEEEEEEECEEEDAAEEEE@CDECDABCEED@D	NM:i:0	MD:Z:108	MC:Z:144M	AS:i:108	XS:i:107	RG:Z:NA12878bgi	SA:Z:chr1,49680389,-,40M104S,0,0;
E100001798L1C022R0062456443	145	chr1	10000	0	51S93M	chr7	131105024	0	GAGAAGTGTGAGAAAAAGAAGCTAAGGATGACTTAAAGTTTTGACCTGAGCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	?EDEEED?5EEADEEEEEEE?>EEECD?D@EDDEEEEEEDEEA;;EEEEE7DEDEECEEE?=CDEC>8DEEEA?@EEE?A9AEEEE:>EEEEECEEECEDEEB?<EEEEEAAFEDCD?EEEE2EEEEEC;FEEE@EEECAABEE	NM:i:0	MD:Z:93	MC:Z:144M	AS:i:93	XS:i:92	RG:Z:NA12878bgi	SA:Z:chr7,131105139,-,52M92S,0,0;
E100001798L1C027R0320878876	121	chr1	10000	0	79S65M	=	10000	0	CTGGTTTATAGCATCGCGAATTTTGACTGCAATATTTCCTCCAGAAAGAGTGACATCTTGTCCTGTGATAAAATCGCTCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	BEEEEDECFEE3DEEEEEEEEEEEEEEEEDEEEEEBECECEEEEEEEEFEE<EEEEEEECEEEEEEEFEEEEEEE;EFEEEDEDEEEEECEEEEEEEEFEDAEEEEEEEEEEEEEEEEEE?EEDEEDEEEBE9DEEEDEEEEEE	NM:i:0	MD:Z:65	AS:i:65	XS:i:64	RG:Z:NA12878bgi
E100001798L1C027R0320878876	181	chr1	10000	0	*	=	10000	0	CTTTATGGAATGCCCTCCCAACATCTGGTAGACAATCCTCCAGGGACGATTTAATCCCAGCCGCCGTGCAGGCCTTAACCACGGCCCACAACTTATGTCTGGGTGTTATTCCAGGTGAGACCTCACACAAGGACACACCCGAGT	EECEEEBAEDEDE@ECEBEEDEEEEEEEEEEEEEEEDEEAEEEEEAEFEEEEBBDECEE9DEEEEEEEEEEEEEEEEEEEEEEEEAE?EE9DECEFEFCEEEEEEEEEEEEEEEEEEEEDECEEEEEEEEEEEEEEEEEEEEEE	MC:Z:79S65M	AS:i:0	XS:i:0	RG:Z:NA12878bgi
E100001798L1C028R0391082482	81	chr1	10000	0	52S58M1I33M	chr6	68720281	0	ATTAGAGTCAGAGATAGAGAAGTACATACAAAAACAGGGGTGTGTGTGAGAAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCC	EEEEEEE0BEEECCEEEFEEEEEE*EEEEEDEEDDEDECEC?EDEBEDE<DDEEEDEDEEEEDEEE=DEEEEDCDDDECDCEEEEBCEEECEEEEEEEECDEEECEEEEECEEEEDEEAEEED:EEEEE*DEEE8D3DEE@E:E	NM:i:1	MD:Z:91	MC:Z:144M	AS:i:84	XS:i:83	RG:Z:NA12878bgi	SA:Z:chr6,68720548,-,51M93S,0,0;
E100001798L1C037R0332432346	145	chr1	10000	0	60S84M	chr3	82016368	0	AAAACCCTGGAAGCAGAAGAGAGACACTGAGAAGAGAGAAGATTCTTCCTTTTTCCAGGAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	D*EDBAE9A/DE@4E.DEEE'A;2E98EEDE>=:@E:7/E-CE8DEDEEE2ED@DE>EDCDE/E@;EEC/DEEDD?7@EEA8@DDE:<@@EEEAEDCEA@E,CEBDE=@EE1D:ADEDE1EEEDDD@EEEE@EEECDE?EDDE8	NM:i:0	MD:Z:84	MC:Z:144M	AS:i:84	XS:i:83	RG:Z:NA12878bgi	SA:Z:chr3,82016452,-,68M76S,0,0;

**Comment by brentp** [comment]
mosdepth just reports the coverage as it is, without considering the reference bases.
