### ISSUE TITLE
Dash in Chromsome Name

### ISSUE THREAD

**Issue by justinjohns** [brentp/mosdepth#115]
Hey Brent, 

Been using mosdepth for years and it's excellent, so thanks. Lately I've been running into an issue when my chromsome names have a dash '-' in them, if I'm trying to specify that region with a bed -b or just the chromosome -c. Maybe I'm missing something obvious.

I'm not familiar enough with python to think of a work around, do you know of a way to remedy this?

`mosdepth -h
mosdepth 0.2.9`

This works as intended, giving per-base output for mtDNA:
`mosdepth -c Mitochondrion --fast-mode ${outdir}/w_coverage/${i}.w ${wd}/${i}.bam;`

This produces an error, it seems to ignore the 'Super-' part of the chromosome name. 
`mosdepth -c Super-Scaffold_52 --fast-mode ${outdir}/w_coverage/${i}.w ${wd}/${i}.bam;
strutils.nim(1096)       parseInt
Error: unhandled exception: invalid integer: Scaffold_52 [ValueError]`

If I instead feed a bedfile, it runs - but it doesn't actually listen to the region parameters. It instead calculates per-base across the entire genome.
Bedfile, tab-delimited (replaced with ':' here to confirm)
`cat ${wchrombed} | awk '{FS="\t"}{OFS=":"}{print $1, $2, $3}'
Super-Scaffold_100259:800001:5947913
Super-Scaffold_52:1:17934201`

And [here's](https://github.com/brentp/mosdepth/files/4511706/JM_Reads.txt) a tiny BAM file with a header in case it's useful.

**Comment by brentp** [comment]
thanks for the clear report. not sure why someone hasn't noticed this before.

I have a fix for this, where there's a '-' in the chromsome name. It still won't work for chromosome names with ':' like HLA, but I'll leave this open till that's fixed.

I'm not sure what you mean about the bed file. If you use `--by $bed` and `-n` then it won't do the per-base. 

Will you try the attached binary and let me know that it resolves the issue you're seeing?
[mosdepth_dev.gz](https://github.com/brentp/mosdepth/files/4512301/mosdepth_dev.gz)

**Comment by justinjohns** [comment]
Hey Brent, works great. Clearer description of the bedfile: I'd like to create a mask for only a subset of chromosomes (sex chroms) with low coverage, so ideally I could feed mosdepth a --by $w_chromosome scaffold list, and calculate per-base on these selected scaffolds (instead of creating a ~9Gb bed file!).

I don't think this is what you intended with --by, and it's not a big deal! This ratchety loop will do it for anyone else who might need this, just need to modify the directories. 

i=bamfile_name
wchrombed=bed file with scaffold IDs

```
for j in $( awk '{print $1}' ${wchrombed} ); do 
    mosdepth -c ${j} --fast-mode ${outdir}/w_coverage/${i}.${j} ${wd}/${i}.bam; 
    zcat ${outdir}/w_coverage/${i}.*per-base.bed.gz > ${outdir}/w_processing/${i}.w_chrom.bed; 
done
```

**Comment by brentp** [comment]
yeah, for the bed file, i think your solution is the best way to go. I'll make a new release with the other fix by next week.

**Comment by skanwal** [comment]
Hi @brentp,

I was reading your comment about using `HLA` as `chrom` and wondering if it is possible to be used?

**Use case:**

I am trying to calculate depth of HLA alt contigs in a BAM. These appear to be in following format:

```
 samtools view -H SEQC-II_Tumor_50pc-ready.bam | grep SQ | grep HLA | wc -l
525

@SQ     SN:HLA-B*44:150 LN:2676 AH:*
@SQ     SN:HLA-B*44:23N LN:3323 AH:*
@SQ     SN:HLA-B*44:26  LN:2804 AH:*
@SQ     SN:HLA-B*44:46  LN:3323 AH:*
@SQ     SN:HLA-B*44:49  LN:3039 AH:*
@SQ     SN:HLA-B*44:56N LN:2676 AH:*
@SQ     SN:HLA-B*45:01:01       LN:3338 AH:*
@SQ     SN:HLA-B*45:04  LN:3339 AH:*
```

**Comment by brentp** [comment]
Hi, yes you can get coverage for those chromosomes. You just can send that argument to -c
