### ISSUE TITLE
using mosdepth with a small RAM

### ISSUE THREAD

**Issue by shouldsee** [brentp/mosdepth#116]
I am working on a cloud machine with 1GB RAM and mosdepth is throwing OOM error. Is there a way I can tell mosdepth to be parismonious?

```python
[
	'export MOSDEPTH_Q0=NO_COVERAGE &&',
	'export MOSDEPTH_Q1=LOW_COVERAGE &&',
	'export MOSDEPTH_Q2=CALLABLE &&',
	'mosdepth',
	'-x -n -t 1',
	'-q 0:100:1000:',
	prefix,
	input_fn,
],
```

**Comment by brentp** [comment]
on human, `mosdepth` will need just over 1GB for chromosome 1. So you'll need a machine with more ram than that. mosdepth trades a bit of memory to get simpler operations and therefore more speed.

**Comment by shouldsee** [comment]
Thank you @brentp! How would you calculate memory usage for different genomes tho?

**Comment by brentp** [comment]
MB of longest chrom * 4 ~ GB of memory use.

**Comment by shouldsee** [comment]
> GB of longest chrom * 4 ~ GB of memory use. so chrom 1 of human is ~0.25 GB. so expect 1GB of memory use.

Got it. Many thanks!
