### ISSUE TITLE
quantize file no accepting bed file

### ISSUE THREAD

**Issue by alexjfortuna** [brentp/mosdepth#118]
hello, quantize with the -b option is not subset by bed region, but the regions file is. Is the this expected behavior?

export MOSDEPTH_Q0=LOW_COVERAGE
export MOSDEPTH_Q1=CALLABLE

bed=headless_S31285117_Padded.bed

mosdepth -b $bed -t 4 -n --quantize 0:79: TS TS.sorted.filter.deduped.realign.recal.bam
mosdepth -b $bed -t 4 -n --quantize 0:29: BC BC.sorted.filter.deduped.realign.recal.bam

**Comment by brentp** [comment]
you mean the quantize file is not subset to bed? That's expected. Since it should be small, you can use bedtools or similar if you want to subset the quantized file.

**Comment by alexjfortuna** [comment]
Ok thank you, just checking expected behavior. thanks for great tool.

**Comment by brentp** [comment]
no problem. with all the combinatorial arrangements of options, some are less than ideal, but i think most are a good compromise.
