### ISSUE TITLE
big_chrom test failed in debian 9 compilation from source (in docker)

### ISSUE THREAD

**Issue by af8** [brentp/mosdepth#123]
Hi, 

I am trying to build mosdepth from source in a debian9 based docker image.

It works perfectly fine when I am doing the same installation on CentSO 7.6. In order, I compile from source : 
1. Nim-1.2.4
2. htslib-1.10.2 with libdeflate-1.6 support (no libcurl and no plugins support)
3. mosdepth-0.2.9

All tests passed and all is good.

But in debian9 the mosdepth-0.2.9 step fails close to the end while running the test named **big_chrom**. The terminal hangs for approximately one minute and then the job `./mosdepth t tests/big.bam` finally gets killed leaving output files empty and the installation naturally stops.
 
In debian, I am starting with this to set up the environment:

```
   apt-get update
&& apt-get install -y git wget curl \
   autoconf automake build-essential \
   zlib1g-dev libbz2-dev liblzma-dev \
   libtool libpcre3-dev
```

Any idea of what could be the reason of this test failure ?

I have tried to install some other system libraries as well but no success so far.

Many thanks,
Anthony

PS: I can provide with a Makefile, links to sources or anything that might be useful.

**Comment by brentp** [comment]
how much memory does the machine have? maybe it's a memory error.

**Comment by af8** [comment]
OK, you are right. It was a memory issue. I am using Docker Desktop for Mac for which memory associated to the deamon is limited by default to 2Gb. I have raised it to 4.5Gb temporarily and the test passed. 

For **big_chrom** test, 4Gb min seems required (seen some memory peaks around 4.2Gb).

![Capture d’écran 2020-07-13 à 10 56 21](https://user-images.githubusercontent.com/16424458/87285776-38acbe80-c4f8-11ea-86d1-940038214830.png)

Things are finally simple and easy whereas I was diving into a lib dependency problem that never existed :-)

Thanks

**Comment by brentp** [comment]
ok. glad to hear it. If the memory is a problem, I can put that test with some kind of (env variable controlled) guard.
