### ISSUE TITLE
"Total" Plot only shows one contig?

### ISSUE THREAD

**Issue by felipe797** [brentp/mosdepth#124]
Hey  @brentp . This is my first time using mosdepth and I'd like to congratulate you on the work you've done. It's a very intuitive and easy tool.  I've been running into a problem everytime I try to plot the coverage, though. I did

`mosdepth mosdepth_out/polished-merged seqL234_merged.bam`
and
`python mosdepth/scripts/plot-dist.py mosdepth_out/*global.dist.txt`
 
the output I get in dist.html shows a "total" plot for only one contig. Here's the image for the plot: 
![Screenshot 2020-07-25 at 6 33 35 AM](https://user-images.githubusercontent.com/59949145/88453818-e9905300-ce40-11ea-92f5-3e1e782711a1.png)

I tried changing the python script to 
`if chrom.startswith(("GL", "AMG", "JH")):`
as you suggested in a previous issue, but the output is still the same.
Any clues as for what is happening?

**Comment by brentp** [comment]
total is the genome-wide coverage distribution. then below, you'll see the coverage distribution for each chromosome.

**Comment by felipe797** [comment]
Oh, I see. I thought "Total" should plot every contig together like you showed in this pic.
Is there a way I can achieve this with your code?

![image](https://user-images.githubusercontent.com/59949145/88458491-bbbd0580-ce64-11ea-8809-49fa45e06494.png)

**Comment by brentp** [comment]
in that plot, every line is a sample and I have plotted 50 or so samples.
you can send multiple dist.txt files and it will show them all.
