### ISSUE TITLE
Different results than shown in BAM

### ISSUE THREAD

**Issue by stanedav** [brentp/mosdepth#125]
Hello, thank you for making this tool for discovering BAM coverage.  I have small issue about different 

I run this command: 
mosdepth --by VP_epi.bed --thresholds 0,1,10,20,30 output intput.bam -Q 10 

But the number of covered bases are not same as if I open my BAM in IGV, example given below:

Output threshold file, one of the lines:
#chrom	start	end	region	0X	1X	10X	20X	30X

chr19 | 13321430 | 13321466 | NM_001127221.1_cds_3_0_chr19_13321431_r | 36 | 36 | 23 | 0 | 0

<img width="1003" alt="Snímek obrazovky 2020-08-11 v 13 30 40" src="https://user-images.githubusercontent.com/14347491/89892586-2dbc7b00-dbd7-11ea-8eef-4de2da29233b.png">

In IGV, I can see that the lowest coverage in this region is 11 - is there any difference in read counts in IGV vs read count by your tool?

**Comment by brentp** [comment]
Well, you asked for read-quality of 10 in mosdepth, but not (AFAICT) in IGV. Mosdepth also adjusts for overlapping mates. There are several closed issues in this repo asking questions like this with regard to samtools depth, bedtools, and others and mosdepth has the correct behavior in all cases as I am sure it does here.
