### ISSUE TITLE
Multiple Options not Taken

### ISSUE THREAD

**Issue by Tine-dk** [brentp/mosdepth#128]
Hi,

I'm new to Mosdepth and would like to play around with the options, but somehow I can only make it work when I give one option and not multiple.

Could you please point me in the right direction? Thanks

These works:
```
mosdepth --by ~/target_files/targets.bed \
GM06891_targetsbed \
/bam/sample.bam
```

```
mosdepth \
GM06891_basic\
/bam/sample.bam
```

But these do not work:
```
mosdepth -n --fastmode --by 500 \
GM06891_500window_fast_n \
/bam/sample.bam
```

```
mosdepth -n --fastmode --by ~/target_files/targets.bed \
GM06891_targetsbed_fast_n \
/bam/sample.bam
```

When I try to run the last two attempts I get the following response as if the program does not understand the setup with multiple options:
`Usage: mosdepth [options] <prefix> <BAM-or-CRAM>`

**Comment by brentp** [comment]
Hi, you just need `--fast-mode` instead of `--fastmode`.

**Comment by brentp** [comment]
... and you can run `mosdepth -h` to see the full set of options.

**Comment by Tine-dk** [comment]
Thank you very much for pointing out my stupid mistake - It works now! Have a nice day/evening. :D
