### ISSUE TITLE
feature request: per base depth in regions

### ISSUE THREAD

**Issue by matthdsm** [brentp/mosdepth#13]
Hi Brent,

How would you feel about adding a flag to calculate the per-base depth for regions in a bed file?
We have a bunch of exome data, and we'd like to calculate the per base coverage of all regions in a given bed file.

Thanks!
M

**Comment by brentp** [comment]
I have a branch `prefix` where it outputs per-base as a bed file. From this, it's a simple bedtools intersect to get the per-base depth in regions. 
I still have some changes to go into that branch. I'll ping this issue when it's merged.

**Comment by matthdsm** [comment]
Hi Brent,
Great to hear! Looking forward to the merge 👍 

Cheers
M

**Comment by brentp** [comment]
this is now implemented in the latest release. 

it's not exactly what you requested but the per-base output is bgzipped and tabixed so you can get the values from a bed file with tabix (or bedtools).

please let me know if this works for you.

**Comment by matthdsm** [comment]
Hi Brent,

Thanks a lot! I'll get back to you when I've tried it out.
In the mean time, I've already updated the conda recipe (https://github.com/bioconda/bioconda-recipes/pull/6263). Hope you don't mind.

Cheers
M

**Comment by brentp** [comment]
closing now. please re-open as needed.
