### ISSUE TITLE
option to increase precision in output files

### ISSUE THREAD

**Issue by brianabernathy** [brentp/mosdepth#133]
Hello,

I'm working with some very low coverage samples and could benefit from more precision in the mosdepth output files. (I'm particularly interested in the mosdepth.summary.txt mean and regions.bed.gz mean fields.) Would it be possible to add an option to increase the number of digits reported to the right of the decimal point? The default output displays 2, 3 would be very useful in my situation.

Thanks,
Brian

**Comment by brentp** [comment]
you can adjust the precision as here: https://github.com/brentp/mosdepth#distribution-only-with-modified-precision
e.g.
```
export MOSDEPTH_PRECISION=5
```

**Comment by brianabernathy** [comment]
Thanks!
