### ISSUE TITLE
Empty plots

### ISSUE THREAD

**Issue by gubrins** [brentp/mosdepth#134]
Heys,
I'm running mosdepth and when I run the python script to obtain the plot, it works but it's empty. I'm working on a non-model organism and the chromosome's names are not the same as humans, so could be this the cause?
I tried to attach the global.dist file but is bigger than 10MB.

Thanks!

**Comment by brentp** [comment]
it's probably just too many chromsomes to plot. you could do:
```
grep ^total my.dist.txt > sub.dist.txt
```
and then just plot the `sub.dist.txt`

**Comment by gubrins** [comment]
It worked perfectly, thanks!
