### ISSUE TITLE
coverage for all the genome

### ISSUE THREAD

**Issue by gubrins** [brentp/mosdepth#135]
Heys again,
I have two quick questions:
First one, I'm interested into discovering the whole coverage of my genome, without any sliding windows, is that possible with mosdepth?
Second one, is it possible to change the Y axes, from "proportion of genome at coverage" to "number of bases" that has that specific coverage?

Thanks!

**Comment by brentp** [comment]
hi,
1. By default, mosdepth will report per-base coverage without a sliding window.
2. Yes, just multiply the proportion by the size of your genome.
hope that helps.

**Comment by gubrins** [comment]
I did not realize that I already had the output I wanted (per-base.bed.gz file), thanks!
