### ISSUE TITLE
Feature request: Threshold to Percentage

### ISSUE THREAD

**Issue by Z-Zen** [brentp/mosdepth#136]
Hello,

Thanks for creating `mosdepth`. I just started using it. However, I have a feature request if possible.

The `-T --thresholds <value>` is a really nice addition to the tool but I don't see the option to output the values as a percentage. For example, if we have 100 base pairs, and 20 are covered in 10X, we would see 20% instead of a number.

Is this possible to have?

Thank you !

**Comment by brentp** [comment]
Hi, this seems a reasonable request, but I won't be adding it. You can make this output yourself by outputting the new d4 format, then using [pyd4](https://github.com/38/pyd4) this will be quite simple.
This will be the solution for any more custom requests for mosdepth in the future.
