### ISSUE TITLE
Update HTSlib constraints, conflicts with latest samtools

### ISSUE THREAD

**Issue by matthdsm** [brentp/mosdepth#146]
Hi,

Would it be possible to update HTSlib for mosdepth? When installing mosdepth together with the latest samtools through bioconda, I'm getting a version conflict
```
Package htslib conflicts for:
samtools==1.12 -> htslib[version='>=1.12,<1.13.0a0']
mosdepth==0.3.1 -> htslib[version='>=1.11,<1.12.0a0']
```

Is this a hard version requirement? Or can we relax the conda recipe?

Thanks
M

**Comment by brentp** [comment]
Hi, anything 1.10 and greater should work without problems.

**Comment by matthdsm** [comment]
Great, thanks!
