### ISSUE TITLE
samtools bedcov & mosdepth

### ISSUE THREAD

**Issue by lmanchon** [brentp/mosdepth#147]
--hi,

i obtain big differences in my results when i use samtools bedcov and mosdepth:

samtools bedcov exome.bed -Q 3 my.bam

chr1    69090   70008   0
chr1    450739  451678  0
chr1    685715  686654  0
chr1    925941  926013  14492
chr1    930154  930336  16345
chr1    931038  931089  6733
chr1    935771  935896  24695
chr1    939039  939129  20591
chr1    939274  939460  25766
chr1    941143  941306  9472
chr1    942135  942251  1778
chr1    942409  942488  1152

mosdepth -t 24 --by exome.bed -Q 3 mybam my.bam

chr1    69090   70008   0.00
chr1    450739  451678  0.00
chr1    685715  686654  0.00
chr1    925941  926013  185.33
chr1    930154  930336  76.90
chr1    931038  931089  124.12
chr1    935771  935896  151.94
chr1    939039  939129  219.56
chr1    939274  939460  122.38
chr1    941143  941306  54.31
chr1    942135  942251  14.27
chr1    942409  942488  11.48

Is the coverage calculation the same?

thx

**Comment by brentp** [comment]
hi, bedcov counts reads, mosdepth reports mean base coverage. see: https://github.com/samtools/samtools/pull/594
also look through the other mosdepth issues for samtools depth, bedtools coverage, and mpileup differences.
