### ISSUE TITLE
Number of reads per target region

### ISSUE THREAD

**Issue by mquinodo** [brentp/mosdepth#148]
Dear Brent,

Your tool is very useful and fast for per position coverage.
What I am looking for is the number of reads per regions in a bed file. I used:
./mosdepth -n -Q 50 -b regions.bed out sample.bam
In the output, I can take out.regions.bed.gz and remultiply by the size of the regions in the bed file.
However, the output in out.regions.bed.gz is rounded to two numbers after decimal and therefore I cant retrieve the number of reads if the average coverage is below 0.01.
Is there a way to avoid the rouding of the output in out.regions.bed.gz?

Thank you and best regards,
Mathieu

**Comment by brentp** [comment]
hi, you can use, for example, `MOSDEPTH_PRECISION=6`
but I think a better solution would be to use a tool that is counting reads instead of coverage. samtools bedcov does this, as does [hts-nim-tools](https://github.com/brentp/hts-nim-tools) count-reads.

**Comment by colindaven** [comment]
I think read counting is an excellent idea to. It would be great to see this implemented. At the moment I'm relying on `samtools idxstats`, and I could go to `featureCounts` or `ht-seq count`, but they both require a GFF3/GTF which would need to be generated.

**Comment by brentp** [comment]
@colindaven does the command in [hts-nim-tools](https://github.com/brentp/hts-nim-tools) meet your needs? it is quite fast

**Comment by colindaven** [comment]
Not sure, I'll evaluate. Thanks for the tip.
