### ISSUE TITLE
mosdepth calculate  uniformity of ngs target sequencing

### ISSUE THREAD

**Issue by worker000000** [brentp/mosdepth#149]
Thanks a lot for making such a powerfule tool, it is really very fast.

# 
`mosdepth --fast-mode --by panel.bed sample-output a.sort.bam -t 4 --d4 --thresholds 1,500,3000`
# 

I want to calculate the uniformity of ngs target sequencing, which defined as base depth nore than the average depth percent

for example, 
uniformity10% mean base depth more than 10% percent of average depth,  if average depth is 500, so it 500*0.1=50, so it needs to calcaulate the base depth percent more than 20.

I found a file ends with .per-base.bed.gz, but it is a file like this
![image](https://user-images.githubusercontent.com/25199946/123506756-7b7b8e00-d698-11eb-9af9-8acb0d95a7a9.png)

# it does not show each base depth of my bed file, though I can calculate average depth from file **.mosdepth.summary.txt**

![image](https://user-images.githubusercontent.com/25199946/123506870-f349b880-d698-11eb-8f24-cd8fced834a0.png)
# 
but I need each base depth, so I can calculate  uniformity10%	uniformity20%	uniformity50%.
# 
if mosdepth can directly calculate different specificed uniformity and on_target base and percetn, it will be more impressive,
# 
though .thresholds.bed.gz is what I can specify the threshold, but before I use mosdepth, I can not calculate the average depth, so I need to rerun modespth if to specify it again of the 10 average depth as thresould

# 
tools like depthof coverage do 
![image](https://user-images.githubusercontent.com/25199946/123507128-6dc70800-d69a-11eb-8ff3-3edf22011848.png)

**Comment by brentp** [comment]
I think you can do what you are describing with the .dist.txt files. The first column in there is the depth and the 2nd column is percent of genome covered at that depth. From that, I think you can get what you need. It has the benefit of being quite a small file as well.

**Comment by worker000000** [comment]
Thanks a lot for your kind reply.
But I do not know what happended, all the second column of my sample-output.mosdepth.global.dist.txt is 0.00

**Comment by brentp** [comment]
your coverage is very low. 
The per-base coverage file indicates that, for example on chrM from base 3254 to 3328, the coverage is 1 read.

**Comment by worker000000** [comment]
Thanks a lot  @brentp 
it is a target dna panel sequence, not including chrM. you can see my chr1 coverage, it is like a real per-base file
![image](https://user-images.githubusercontent.com/25199946/124137817-9eeb7200-dab8-11eb-8cd6-43c1b73529c9.png)

but for some low coverage postion, it merged again, which is not what I want
![image](https://user-images.githubusercontent.com/25199946/124137988-ccd0b680-dab8-11eb-8a22-28b118ab75d3.png)
#  
to calculate uniformality, I  need the real per-base file, how can I get that, is there any argument? Thanks a lot

**Comment by brentp** [comment]
Oh, the per-base file tries to merge adjacent sites, so if you have 100 consecutive bases with depth 33, then that will appear as a single line. 

And I think what you need is in the dist file. Its just that iit's showing that you have e.g. 0.00% coverage at 5524X coverage. If you scroll through that file, eventually, you'll see (in the 2nd column), lower coverage numbers and the percentage in the 3rd column will increase.

**Comment by worker000000** [comment]
Thanks a lot @brentp 
Because my understanding is poor，I wan to say the third column is what percentage, for example, 
chr19	125	0.01   # does it mean the base of 125x  accounts for the 0.01 of the total length of chr19 (chr19   59128983  about 59M base), does here mean 125x is about 0.59M base?  this is not that accurate, I guess
![image](https://user-images.githubusercontent.com/25199946/124141609-22f32900-dabc-11eb-8816-6f84932aac1b.png)

# 
I entered a bed file, but the mosdepth seems to does not use it except in sample-output.mosdepth.summary.txt
![image](https://user-images.githubusercontent.com/25199946/124144307-6d75a500-dabe-11eb-8b62-bf9e9b98ada4.png)
#  
here you can the total and the different chr  differs a lot, here I filter third colum which is 0.00, you can the total ignore many other depth which is not 0
![image](https://user-images.githubusercontent.com/25199946/124144492-9dbd4380-dabe-11eb-9c57-19a56b592d4c.png)

# thie file what I want is the bed file I supplied., and it gives the each base depth of that file,

**Comment by brentp** [comment]
A row like this:
```
chr2  33 0.51
```
would mean that ~51% of chr2 is at coverge 33 or higher.
If that's in $prefix.dist.txt, the nit's for the entire chrom. If that's in $prefix.regions.dist.txt then it's for the regions (your panel.bed).

**Comment by worker000000** [comment]
Thanks a  lot @brentp 
A chromosome is really always large compared to a tageted panel(which is always 0.1M to 2.5M), but the result just 2 decimal places reserved，I think  results will be very different.

# 
the $prefix.regions.dist.txt then it's for the regions, do you mean the second column stands for the depth, the third column stands for the base depth no less than the second column number in the bed region of corresponding chromosome
chr1    316     0.99  does it stands for 99% region of chr1 in the bed deoth no less than 316?
do you find here lack number 317
![image](https://user-images.githubusercontent.com/25199946/124212131-fde4d180-db20-11eb-86f9-b590a6d05d3c.png)

#   
taking all the above infromation, it is still not able to calculate Uniformity, because the Importance of Coverage
Uniformity Over On-Target Rate for Efficient Targeted NGS.
I can get the average depth from sample-output.mosdepth.summary.txt, for example average depth is 5000x, and I want to calculate  Uniformity_0.1x(base rate of depth more than 5000*0.1), eg, but due the number in the $prefix.regions.dist.txt is not completed continous, I will miss the number definitely，and the rate is not accuratley enough for ngs panel, I think 4-6 decimal is needed.

# 
Sorry for my lengthy statement and request

**Comment by brentp** [comment]
That means that there are no bases with exactly 317X coverage so you can set it to same as 318.
You can also get more precision on that output with ,,e.g.:
```
export MOSDEPTH_PRECISION=8
```
to get 8 instead of 2

**Comment by worker000000** [comment]
Thanks a lot @brentp 
But for a automatic program, I can not except the value gap of what I want , maybe 1, maybe 100, but the program need a exact value, can I force the program to output each base, it is really what I want

**Comment by worker000000** [comment]
Thanks a lot @brentp
do you have time to have a look at my question

**Comment by worker000000** [comment]
Thanks a lot @brentp
do you have time to have a look at my question

**Comment by brentp** [comment]
I don't know how to help you. If you have a specific question, I will try to answer.

**Comment by worker000000** [comment]
Thanks a lot @brentp

the $prefix.regions.dist.txt then it's for the regions, do you mean the second column stands for the depth, the third column stands for the base depth no less than the second column number in the bed region of corresponding chromosome

![image](https://user-images.githubusercontent.com/25199946/125180687-75a4b180-e22f-11eb-8f1b-e7933120394c.png)

# 
I want it show each number, but no lack number like 317, because this time its gap is 11, it can not be sure if change to another sample, the gap is what?

**Comment by brentp** [comment]
I'll paste my response from earlier. After this, I'm not sure how to help you.

"That means that there are no bases with exactly 317X coverage so you can set it to same as 318."

**Comment by worker000000** [comment]
can I force to output each, I do not want it to merge

**Comment by worker000000** [comment]
@brentp is there any advice about  force to output each

**Comment by brentp** [comment]
Hi, one last try. It appears however, that, I am not able to help you. Note that I previously stated:

"That means that there are no bases with exactly 317X coverage so you can set it to same as 318."
So if you see:

```
chr1 318 0.99
chr1 316 0.99
```
this means that no bases have exactly 317X coverage, but you can set that to 0.99 (same as the value above).

mosdepth will not output this number. But you can add it yourself.
