### ISSUE TITLE
Feature request: Option to discard incomplete windows and short contigs

### ISSUE THREAD

**Issue by hannesbecher** [brentp/mosdepth#150]
Hi there, very nice piece of software!

This is about the window mode. I am wondering, would it be possible to add a flag to make `mosdept` discard from the output those contigs and windows (at the end of contigs) that are shorter than the value set with `-b integer`? I personally would find that most useful.

Cheers

**Comment by brentp** [comment]
Hi, this is easily done with awk, so I won't add it to mosdepth:
```
zcat $bed | awk '$3 - $2 >= 100' | bgzip -c > $newbed
```
