### ISSUE TITLE
Plot coverage with mosdepth

### ISSUE THREAD

**Issue by assane-mbodj** [brentp/mosdepth#155]
Hello, thank you for this wonderful tool that makes it easier for us to calculate the average coverage

This is the first time I am doing coverage analysis and I would like to understand the results of the plot output please.
How can we interpret the attached plots and what is the output of the following command:

assane@gwas:~/mosdepth-0.3.1$ python scripts/plot-dist.py PO10_illlumina/*.mosdepth.global.dist.txt
PO10_illlumina/sample.wgs	Chr1	18	0.560
PO10_illlumina/sample.wgs	Chr2	19	0.510
PO10_illlumina/sample.wgs	Chr3	19	0.510
PO10_illlumina/sample.wgs	Chr4	18	0.560
PO10_illlumina/sample.wgs	Chr5	19	0.510
PO10_illlumina/sample.wgs	ChrC	3441	0.510
PO10_illlumina/sample.wgs	ChrM	149	0.510
PO10_illlumina/sample.wgs	total	19	0.510
assane@gwas:~/mosdepth-0.3.1$ python scripts/plot-dist.py -o PO10_nanopore/PO10nanopore_global.html PO10_nanopore/*.mosdepth.global.dist.txt
PO10_nanopore/PO10.wgs	Chr1	56	0.530
PO10_nanopore/PO10.wgs	Chr2	56	0.510
PO10_nanopore/PO10.wgs	Chr3	55	0.540
PO10_nanopore/PO10.wgs	Chr4	55	0.540
PO10_nanopore/PO10.wgs	Chr5	56	0.530
PO10_nanopore/PO10.wgs	ChrC	11830	0.510
PO10_nanopore/PO10.wgs	ChrM	334	0.510
PO10_nanopore/PO10.wgs	total	56	0.520

What do the last two columns represent?

[PO10.zip](https://github.com/brentp/mosdepth/files/6867778/PO10.zip)

Your help to explain the plots would be very useful for the continuation of my analysis
Thanks
Assane

**Comment by brentp** [comment]
The plot script outputs, for each chromosome, the line where the depth (3rd column) is closest to 50% (4th column).

This means, for this line: `PO10_nanopore/PO10.wgs total 56 0.520` that 52% of your *total* genome is at or above 56X coverage.

**Comment by assane-mbodj** [comment]
Thanks for your answer 
I also wanted to know why the average coverage is 78 on the file PO10.wgs.mosdepth.summary.txt attached below while it is 52 on the plot
[PO10.wgs.mosdepth.summary.zip](https://github.com/brentp/mosdepth/files/6868693/PO10.wgs.mosdepth.summary.zip)
Thanks
