### ISSUE TITLE
Coverage 0 but reads found

### ISSUE THREAD

**Issue by jaesvi** [brentp/mosdepth#157]
Hi,
Thanks for this tool, I use it frequently. I have found one case though where mosdepth outputs coverage 0 for a region of interest but I see reads on IGV. I then subset the BAM file to my region of interest (chrY:12000000-12100000)  and running mosdepth on the subset does give me the expected output (with coverage between 40 and 50). The command used was:
`mosdepth -n --fast-mode --by 500 test test.bam` (with
 -t 4 for the full BAM). Mosdepth version is 0.3.1.  Any idea why this could happen? I attach the bed output (sliced for the region of interest) in both cases, do let me know if I can send something else. 
[full.regions.bed.gz](https://github.com/brentp/mosdepth/files/7122037/full.regions.bed.gz)
[subset.regions.bed.gz](https://github.com/brentp/mosdepth/files/7122040/subset.regions.bed.gz)

Thanks,
Jose

**Comment by brentp** [comment]
are you using mosdepth downloaded from the github releases? if not, can you try that version?
if so, would it be possible to share the relevant portion of the bam file?

**Comment by jaesvi** [comment]
I am using the bioconda version, I can test the github one indeed. 
[test.bam.gz](https://github.com/brentp/mosdepth/files/7122241/test.bam.gz)
This is the relevant BAM but this one works as expected.

**Comment by PattSS** [comment]
Hi,
I am having a similar problem. 

I am running mosdepth version 0.2.4 and 0.3.2. The command and BAM file are the same:
export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 16 -F 1804 -Q 1 --no-per-base --by target-genome.bed --quantize 0:1:5: regions_sample sample.bam

If I used mosdepth v0.2.4 the first region considered "callable" at chr10 is: 
10	92938	95423	CALLABLE

Instead, if I used modepth v0.3.2, the first region considered "callable" at chr 10 is:
10	131020	131809	CALLABLE

Do you have any idea why this is happening?
Thank you in advance.
Patricia

**Comment by brentp** [comment]
Hi Patricia,
v0.2.4 was released > 2 years ago so there have been many changes. I think that the relevant changes could be in 2ec57ea , 767515c, and 6826327
these were related to how overlapping pairs were handled.

**Comment by brentp** [comment]
Hi Jose, #153 is only relevant if you are using the `-R` option. The differences between v0.3.1 and v0.3.2 should not affect you. You can verify this by also running the v0.3.1 binary from the github releases on your data.
I suspect that the version with the problem is using a version of htslib with a bug.

**Comment by PattSS** [comment]
Hi,
Thank you for your quick answer. 
I thought that the problem could be related with the properly paired reads. But, when I use samtools to extract only reads with the flag -F 1804 and I run the same command using this new BAM file, the output from mosdepth v0.3.2 is similar to the output from v0.2.4. I am runing mosdepth in docker (biocontainers / mosdepth). Can it be related with that?

**Comment by brentp** [comment]
it seems that the container version is broken somehow. i don't know how those are created. can you try with the 0.3.1 binary from the releases?

**Comment by PattSS** [comment]
I tried with version 0.3.1 from the releases and it works! Thank you very much for your help.

**Comment by jaesvi** [comment]
I guess indeed that in conda/docker versions there is something weird going on with htslib. Thanks for your help.
