### ISSUE TITLE
mosdepth.global.dist.txt third column

### ISSUE THREAD

**Issue by asmlgkj** [brentp/mosdepth#158]
thanks a lot for building such a fast tool.
what does the meaning **of third column** stand for, the whole chromosome or the corressponding chromosome or something else?
![image](https://user-images.githubusercontent.com/50854682/134347774-e019abd1-8bba-4e3d-a67f-dc2afbadaeac.png)

**Comment by asmlgkj** [comment]
is the total region or total ?
![image](https://user-images.githubusercontent.com/50854682/134348423-7b93f95d-e3ed-4008-8551-e9b6f254b150.png)

**Comment by brentp** [comment]
global.dist is always for all bases on the chromosome. the number in the 3rd column indicates the proportion of bases that have a coverage higher than the number in the 2nd column.

the summary file splits by region and total (as you can see).

and the regions.dist.txt is always for only bases within the specify regions (--by).

**Comment by asmlgkj** [comment]
but when I sum the third column of *dist file
awk -F"\t" 'BEGIN{sum=0}{ {sum+=$3}}END{print sum}' S207.mosdepth.global.dist.txt
it is 114.844,
awk -F"\t" 'BEGIN{sum=0}{ if ($1=="chr1"){sum+=$3}}END{print sum}' S207.mosdepth.global.dist.txt
2.27143
neither of each sum is 1, is this normal.

**Comment by asmlgkj** [comment]
I got mean depth of my bed region is 1012.27517717 from S207.mosdepth.summary.txt, I want to get 0.1 uniformality , 0.2x uniformality , 0.5x uniformality

**Comment by brentp** [comment]
The values in the dist.txt files are the CDF, not the PDF, so won't sum to 1. 
Even if they were the PDF, then you have a PDF for each chrom so you'd need to do it by chromosome.

> I do think if mosdepth can output each depth (>=) percentage, it solves the uniformality issue, once for all

mosdepth outputs percentage (really ratio) >= depth.

**Comment by asmlgkj** [comment]
thanks a lot, really wonderful tool,

**Comment by asmlgkj** [comment]
does the fourth column stand for the mean depth in this region? thanks a lot
![image](https://user-images.githubusercontent.com/50854682/134371534-198aa65b-b328-4466-a42b-c439314ed976.png)

**Comment by asmlgkj** [comment]
thanks a lot

**Comment by brentp** [comment]
i think samtools depth is using 1-based coordinates. mosdepth is bed, which is 0-based half-open.
