### ISSUE TITLE
Feature Request - base quality filter

### ISSUE THREAD

**Issue by jasper1918** [brentp/mosdepth#16]
Hey Brent,

Mosdepth is pulling some impressive timings for some deep WGS samples I am running--well done.

I typically use sambamba or samtools to get coverage stats and would like to switch over. One thing missing here though and also with `goleft depth` is the ability to filter on base qualities. Any particular reason you have not implemented?

**Comment by brentp** [comment]
This is not possible given the way that mosdepth is implemented. If you need per-base, then samtools depth is your best bet. mosdepth is fast because it avoids processing each base--which samtools does.

**Comment by jasper1918** [comment]
Understood and I figured to be the case after a cursory view of the code. Thanks!

**Comment by brentp** [comment]
sure. please let me know any other issues. I also assume that using base-quality (unless it's a very high threshold) is unlikely to change the depth results, but I haven't actually verified that.
