### ISSUE TITLE
Retrieve Index File

### ISSUE THREAD

**Issue by priyambial123** [brentp/mosdepth#163]
Hello

Using **pbmm2**, I aligned the reference genome and bam file. In the next step, using **mosdepth**, I am tried to calculate depth for set of genomic regions (bam file resulted from the alignment step). When I run the command,  

mosdepth --by capture.bed sample-output ref.movie.bam ##ref.movie.bam is the aligned bam file. I get the below error message:

[E::idx_find_and_load] Could not retrieve index file for 'ref.movie.bam'

How to index the bam file? Use Samtools to index the bam file. 

I am following the pipeline followed for hifi reads in the given link:https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake

Thanks 
Priya

**Comment by brentp** [comment]
did you use `samtools index ref.movie.bam` ? and is there then a `ref.movie.bam.bai`?

**Comment by priyambial123** [comment]
Thank you. Yes I could get the index file using samtools. Where to download the capture.bed file to calculate the coverage in exon capture region

Priya








On Thursday, 2 December, 2021, 02:28:09 pm GMT+1, Brent Pedersen ***@***.***> wrote: 







did you use samtools index ref.movie.bam ? and is there then a ref.movie.bam.bai?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brentp** [comment]
Hi, I won't be able to help you get the capture.bed. That would depend on the exome capture kit that was used.
