### ISSUE TITLE
Discrepancy between mosdepth coverage and bam profiles on IGV

### ISSUE THREAD

**Issue by alhafidzhamdan** [brentp/mosdepth#164]
Hi there,
I have an ONT bam file that i ran mosdepth for coverage using this:
$MOSDEPTH --fast-mode -t 4 $SAMPLE $NGMLR_BAM 
I plotted the coverage per region and in my region of interest i see this huge spike up 
![image](https://user-images.githubusercontent.com/53702866/145609445-24116e55-580f-497b-b72a-a3ab91c8b6ee.png)

However, this does not correspond at all with the bam profile on IGV - in fact it's the oppposite- barely any reads in the region showing very high coverage.
![image](https://user-images.githubusercontent.com/53702866/145609246-1850b62d-1e1b-49ff-bfaa-bb3992ded082.png)

I wonder if anyone has come across this? Do you have any ideas as to why this occured?
Thanks!
A

**Comment by brentp** [comment]
Hi, can you show a few lines of the per-base file with coverage > 150? Then we can be sure you are looking at the same region in IGV.

**Comment by alhafidzhamdan** [comment]
Hi yes, in R.

```
E34_cov %>% dplyr::filter(V1 == "chr7" & V4 > 150) %>% head()
    V1       V2       V3  V4
1 chr7 56369552 56369599 151
2 chr7 56369599 56369610 152
3 chr7 56369610 56369614 151
4 chr7 56369614 56369618 152
5 chr7 56369618 56369621 153
6 chr7 56369621 56369625 154
```

A

**Comment by brentp** [comment]
OK. Then can you zoom into that region in IGV?
The things that come to mind are reads with mapping-quality of 0. Those are counted by default in `mosdepth`. But you can exclude them by using `-Q 1` argument.
You may have to configure igv to show reads with mapping-quality 0 as well.

**Comment by alhafidzhamdan** [comment]
Got it! 
I'll filter mosdepth by read quality then (didn't realise this is not default).
Cheers.
A

![igv_snapshot](https://user-images.githubusercontent.com/53702866/145621859-5bf24e4a-e8e4-4861-8754-70ea62c2e4fa.png)
