### ISSUE TITLE
How to calculate % ( what % is 10X, 30X, 50%) along with 1,10,20,30X

### ISSUE THREAD

**Issue by Kiran936** [brentp/mosdepth#166]
Hi,

How to calculate % ( what % is 10X, 30X, 50%) along with 1,10,20,30X as BAM and BED Input

**Comment by brentp** [comment]
If you look at the regions.dist.txt (global-dist.txt) file, you'll see that in there. 1 column is the coverage and 2nd column is percent of regions (genome) at that coverage

**Comment by Kiran936** [comment]
This wont address the question i asked

**Comment by brentp** [comment]
if you want help, you'll have to ask a clear question.

**Comment by aspitaleri** [comment]
Hi
I did with a bash script dividing the nucleotide length at 10X for the theoretical length of the gene/genome. For instance:

```
a=`head -n 2 ${DIR}${i}/coverage.mosdepth.summary.txt| grep -v chrom | awk -F'\t' '{print $4}'`
zcat ${DIR}${i}/coverage.thresholds.bed.gz | awk -v i=$i -v a=$a -F'\t' '{if($1 !~ /^#/) print i,$4,a,$5/($3-$2),$6/($3-$2),$7/($3-$2),$8/($3-$2),$9/($3-$2),$10/($3-$2),$11/($3-$2)}' OFS='\t' 
```
HTH

**Comment by Kiran936** [comment]
@aspitaleri  Thanks a ton, this is exactly i wanted, Cheers
