### ISSUE TITLE
SIGSEGV issues reported when running mosdepth 

### ISSUE THREAD

**Issue by JiaweiShen1116** [brentp/mosdepth#167]
Hi, 

I am currently running mosdepth on some of the bam files to generate the depth and coverage stats. However, it reports the following error: 
<img width="780" alt="Screen Shot 2022-01-10 at 11 58 26" src="https://user-images.githubusercontent.com/72170938/148836414-5fdb69f6-59e2-413e-9e3b-4e89f9bf8b48.png">

I did some search online and it indicated that the SIGSEGV error means signal for memory access violation. I also ran mosdepth on some other bam files I have and it worked normally. Does this indicate some issue with the bam file? Thank you very much.

Best,
Jiawei Shen

**Comment by brentp** [comment]
I'd guess this means you don't have write access in that directory.
