### ISSUE TITLE
Custom index pointer

### ISSUE THREAD

**Issue by philip-scorpiontx** [brentp/mosdepth#168]
Samtools [since a few months allows you to point to a custom index file](https://github.com/samtools/samtools/commit/c8c76865d81cebfa0eb9cf139155555fcf254a50) via the `-X` argument. Would you be able to implement a similar solution for scenarios where the index file doesn't live in the same directory as the BAM, has a different name, etc.?

**Comment by brentp** [comment]
This should be possible. I'll have a look this weekend. Meanwhile, you could always softlink the index to the directory where the bam is.

**Comment by philip-scorpiontx** [comment]
Thank you! I have a specific use case where softlinking isn't possible otherwise I would have resorted to that.

**Comment by brentp** [comment]
if that works, I'll tag a new release.

**Comment by philip-scorpiontx** [comment]
Swift work, thanks!

I'm getting `zsh: exec format error: ./mosdepth`.

**Comment by brentp** [comment]
Are you on linux? a relatively recent machine?

**Comment by brentp** [comment]
and did you `chmod +x ./mosdepth` ? (I don't know if zsh shows the same error for that).

**Comment by philip-scorpiontx** [comment]
I'm on a MacBook (thus zsh), and I did chmod before trying. It seems to run on a regular linux box I have access to, so I can try there.

**Comment by philip-scorpiontx** [comment]
Yes, that worked as intended.

**Comment by brentp** [comment]
thanks for verifying. I'll make a release this weekend.

**Comment by brentp** [comment]
Thank you for verifying. I'll have a new release out in a couple hours or less.
