### ISSUE TITLE
How to use flag option?

### ISSUE THREAD

**Issue by Nonodayo** [brentp/mosdepth#169]
I want to know the read with specific flags.
The codes are like following.

MOSDEPTH_PRECISION=5 mosdepth -n -i 4  something.bam

But I couldn't find any reads with the flag.
Could you inform me how to use the flag option?

**Comment by brentp** [comment]
-i 4 means you want only include unmapped reads which wont work for finding coverage. What are you trying to do?

**Comment by Nonodayo** [comment]
I misunderstood the meaning of the flag. I'm sorry to ask you a strange question. Thank you for your responce.

**Comment by brentp** [comment]
no problem. glad that resolved it.
