### ISSUE TITLE
Region-level distribution

### ISSUE THREAD

**Issue by vladsaveliev** [brentp/mosdepth#17]
Hi Brent, 

What do you think about adding a feature to report % of an interval covered at certain depth thresholds? Similar to `sambamba depth` with `-T` options:
```
sambamba depth region sample.bam -L regions.bed -T 1 -T 10 -T 30
```
Which outputs:
```
chrom  chromStart  chromEnd  F3  readCount  meanCoverage  percentage1  percentage10  percentage30  sampleName
chr21  9483184     9483680   .   225        33.7641       100          98.7903       73.9919       sample
...
```
It gives information to detect poorly and unevenly covered regions, useful to inspect quality of capture and amplicon panels.

Bcbio used to report this with sambamba and will miss it with full migration to mosdepth, so another reason to have it is that it'll allow to migrate without loosing anything. cc @chapmanb

Vlad

**Comment by brentp** [comment]
I think this should be possible and something that fits within the constraints dictated by how mosdepth does its counting. I'll have a look at this soon--though it might be after ASHG next week.

BTW, do you guys have any metrics on how much mosdepth speeds up the coverage portion of bcbio?

**Comment by brentp** [comment]
Here are some putative docs for the proposed feature to help me brainstorm:

## per-region thresholds

If `--by` is specified, a user can request to see how many bases in each interval are covered at a set of thresholds. For example to see, how many bases are covered at 1X,10X, 30X:

```
mosdepth --by some.regions.bed -T 1,10,30 $prefix $bam
```

this will create (in addition to the other output files) `$prefix.threshold.bed.gz`
where the 4th, 5th, 6th columns are respectively the number of bases covered by at least 1, 10, 30 reads. 

The help in the tool will look like:

```
  -T --thresholds <thresholds>     report bases for each --by interval covered at these (comma-delimited) depths.
```

or it could be `-N`, `--n-bases-gte`.

Any feedback on this plan @vladsaveliev or @chapmanb ?

**Comment by vladsaveliev** [comment]
That sounds great to me. Though I would personally output into the same file, using additional columns (like sambamba does); but that's just the matter of taste.

**Comment by chapmanb** [comment]
Brent;
Thanks so much for considering this. The proposed functionality looks great to me, and I prefer the `--thresholds` naming over `--n-bases-gte`.

For timings, we saw a ~3x speedup when replacing sambamba depth calculations in our QC calculations. I didn't yet do timing on the coverage calculations for parallelization but expect a similar improvement. Adding in thresholding, assuming it doesn't add a lot of additional runtime, would save another step so be an effective 6x speedup.

Thanks again for all the great work on mosdepth, the current bcbio development version uses it for all our coverage calculations.

**Comment by vladsaveliev** [comment]
I implemented new mosdepth changes into bcbio. As soon as the updated mosdepth is released, will throw a pull request there.

**Comment by brentp** [comment]
Great! I will release next week. More the in a recent commit I have added a header line to the output.
It is prefixed with #.
Thanks for the feedback and ideas and keep them coming.

**Comment by brentp** [comment]
this is out here: https://github.com/brentp/mosdepth/releases/tag/v0.2.0

**Comment by vladsaveliev** [comment]
Thanks a lot!
