### ISSUE TITLE
mosdepth.summary.txt region differs much with bed region

### ISSUE THREAD

**Issue by asmlgkj** [brentp/mosdepth#172]
after rerun, it solved, but I did not get error in the first time,

**Comment by brentp** [comment]
what is the output of 
```
awk '$0 !~ /^#/ { s += $3 - $2 } END{ print s}' $bed
```
where $bed was your regions file?

**Comment by asmlgkj** [comment]
the ontarget rate is 66%, the Clean bases is 1014.6M, the average depth is 965.49, coverage rate is 28.79%, 0.1x uniformity is 22.2%,  rergion ratio no less than 500x is 20.42%

**Comment by brentp** [comment]
what command are you using to run mosdepth?

**Comment by asmlgkj** [comment]
after rerun, it solved, but I did not get error in the first time,

**Comment by asmlgkj** [comment]
sorry for the disturb, I closed it
