### ISSUE TITLE
error: unhandled exception: invalid integer: 0.065 [ValueError]

### ISSUE THREAD

**Issue by asmlgkj** [brentp/mosdepth#174]
Thanks  a lot for this great tool.
I found it can cause error, if mean depth is low, for example my mean depth is 0.65, so if I want to get the 0.1x  Uniformity, 
command

mosdepth --fast-mode --by xx.bed -t 4 --thresholds 0.065 -Q 30
it will give such error

<br>
this situation maybe also in wgs data, which the mean depth is very low. my above example is a low quality ngs panel data

**Comment by asmlgkj** [comment]
yes, but if that, the integer wiill be 0, so the 0.1x Uniformity will be 100%, which is not right

**Comment by brentp** [comment]
thresholds is not the means to do what you want.
you can make a histogram of the mean depths in the 4th column of the output.regions file or you can use the summary.
