### ISSUE TITLE
sorting issue

### ISSUE THREAD

**Issue by mpalatucci** [brentp/mosdepth#177]
Hi all I was hoping to find help here.

I am doing some ATAC_Seq analysis.

I am trying to compare peak callers Genrich (atac-seq specific) and MACS2 for the same dataset
From what I have read, because I'm dealing with paired end reads, it makes the most sense to sort my final bam files by name. In addition, Genrich requires you to sort the bam files by name for the peak calling.

Due to the sorting by name, I'm running into issues with differential peak calling with diffbind, which requires the bam files to be sorted by coordinates. 

soo... I have a couple questions i'm hoping to receive some clarification on:

1. is it ok if my bam files for diffbind are sorted by coordinate but my peaks were called by name sorting?
2. are there any discrepancies this differential sorting of bam and peak files may cause that I should be aware of ?

any help greatly appreciated!

**Comment by brentp** [comment]
In order to use mosdepth, your data must be coordinate sorted. I don't know about peak calling, that would depend on the tool that's used for that application.
