### ISSUE TITLE
Error building 0.3.3

### ISSUE THREAD

**Issue by zlskidmore** [brentp/mosdepth#181]
Hi, 

I am running into an issue related to d4 when trying build the latest mosdepth release:

```
#35 158.2 CC: ../../../../root/.nimble/pkgs/d4-0.0.3/d4pkg/d4_sys.nim
#35 158.2 CC: ../../../../root/.nimble/pkgs/d4-0.0.3/d4.nim
#35 158.3 CC: mosdepth.nim
#35 158.3 /root/.cache/nim/mosdepth_d/@m..@s..@s..@s..@sroot@s.nimble@spkgs@sd4-0.0.3@sd4.nim.c:8:10: fatal error: d4.h: No such file or directory
#35 158.3  #include <d4.h>
#35 158.3           ^~~~~~
#35 158.3 compilation terminated.
```

Seems like the relevant line, I'm a bit loss as to how to clear this error when running the function-tests.sh script. FWIW all other tests complete successfully. I did install d4tools thinking that the d4.h file might then be found, but this did not seem to work either.

**Comment by brentp** [comment]
Hi, if you don't need d4 support, you can ignore this problem. Otherwise, you'll have to install d4 to a standard location or one that the compiler can find.
If you build mosdepth without the d4 defined, like:
```
nim c -d:danger mosdepth.nim
```
then you should have a working binary (without d4 support)
