### ISSUE TITLE
--by capture.bed still give out region not in bed

### ISSUE THREAD

**Issue by worker000000** [brentp/mosdepth#182]
Dear professor,
thanks a lot
I have a bam generated by a capture bed 1, and I used bed 2 (bed 2 is a gene exon region, 16 exons (16 lines in bed)).
when I ran mosdepth --by capture.bed sample-output sample.exome.bam.
my interested file is sample-output.per-base.bed.gz
it still gives other region not what I want (region not just in bed 2), how can I prevent such issue.
because I want to evaluate the sequence cover of just my interested gene region

**Comment by brentp** [comment]
per-base always has all bases in the genome.
you can intersect that with your exons or look at regions.bed

**Comment by worker000000** [comment]
Thanks a lot @brentp 
But regionds.bed is a mean depth of region, sometimers we want to evaluate the coverage of per-base in specific region.
for example, We want to know whether  each base of gene A is sequence covered, we may achieve this by artificial made a bed file base by base.  can mosdepth add this function?

**Comment by brentp** [comment]
Hi,
you can use --thresholds to find how many bases are covered at a (number of) given threshold(s). 
Or you can use the regions.bed to intersect or query your per-base.bed.gz or you can simply use tabix on the already indexed per-based.bed.gz
I think you can get a lot of what you want with --thresholds e.g --thresholds 1,5,10 will give you a column each indicating the number of bases covered by at least 1, 5, and then 10 bases.

**Comment by worker000000** [comment]
Thanks a lot @brentp
intersect with  per-base.bed.gz is a good idea

**Comment by blajoie** [comment]
Also looking for per base, but only for positions in the supplied bed.  Tge below produced a 5.1G genome wide per-base coverage bed.  Ideally it would have only been composed of a few thousand positions.

Perhaps if -n is not supplied then --by should not be allowed, since it is in essence ignored silently?

```mosdepth --by mybed4.bed sample.target-cov sample.deduped.bam  -x -t 6```

**Comment by brentp** [comment]
Hi, I agree it would be nice to have that option to only output bases in the --by, but I don't intend to implement since that's easily had by later intersection or tabix'ing.
