### ISSUE TITLE
how coverage in region is calculated

### ISSUE THREAD

**Issue by xiaoyunguo** [brentp/mosdepth#183]
Hi 

Thanks for developing this great tool!

I have a naive question, how is the coverage in a region calculated? Is it reads per unit length? so if I normalized the coverage with library size and x1e9, I got RPKM? 

Thanks

**Comment by brentp** [comment]
The coverage is the number of aligned bases (meeting mapq threshold) that cover each region base.
Note that when using --fast-mode deletions will also be counted as aligned bases.
