### ISSUE TITLE
Support for streaming

### ISSUE THREAD

**Issue by multimeric** [brentp/mosdepth#189]
Hi, it seems that mosdepth doesn't support reading from stdin:

```bash
$ mosdepth output - < foo.bam
[E::hts_hopen] Failed to open file -
[E::hts_open_format] Failed to open file "-" : Exec format error
[hts-nim] could not open '-'. Exec format error
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
$ mosdepth output < foo.bam
Usage: mosdepth [options] <prefix> <BAM-or-CRAM>
error parsing arguments
```

Is it possible to add this feature? Or is the ability to randomly access reads in the alignment a requirement for mosdepth?

**Comment by brentp** [comment]
Unfortunately, this is not supported and will not be. The file must be on disk and indexed.

**Comment by cjw85** [comment]
+1  on this. We have various little bits of BAM preprocessing and QC steps in our workflows, and would like to minimise the CPU hours spent in libdeflate.
