### ISSUE TITLE
./mosdepth: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./mosdepth)

### ISSUE THREAD

**Issue by crazyhottommy** [brentp/mosdepth#19]
Hi,

I got this error and googled around. it lacks library GLIBC_2.14 on our cluster. I tried to install that lib, but so far no luck. anything else on your side can help?

Thank you,
TOmmy

**Comment by brentp** [comment]
are you using the mosdepth from bioconda?

**Comment by crazyhottommy** [comment]
no, I downloaded the binary.

**Comment by brentp** [comment]
yeah. if you have this problem the one from bioconda should fix it for you.

**Comment by crazyhottommy** [comment]
thanks. that fixed it.

**Comment by brentp** [comment]
thanks for following up. in the future, I'll poach the bioconda release and add it to the releases here to make it more apparent.
