### ISSUE TITLE
depth per strand

### ISSUE THREAD

**Issue by onordesjo** [brentp/mosdepth#192]
Hi @brentp, thanks for an awesome tool.

Often it's useful to have depth statistics (especially in the per-base.bed.gz) per strand. It's possible, albeit not convenient to subset a bam before running mosdepth into forward and reverse strands. I was wondering if you have a suggestion for a cleaner way of doing it. Do you think it would be possible to include a `--stranded` option (or something similar) that will partition the individual reads by strand upstream, and perhaps output fwd depth with `.fwd.` and reverse depth with `.rev.`? If not, would you suggest subsetting the bam with `samtools view` upstream, or is there any other workaround?

Thanks

**Comment by brentp** [comment]
Hi, `mosdepth` lets you specify [sam flags](https://broadinstitute.github.io/picard/explain-flags.html) to be required or excluded. You can use this to first include only reads on reverse strand: `-i 16` and then to exclue reads on the reverse strand: `-F 1812` where `1812` is `1796 | 16` where `1796` is the default which excludes supplementary, secondary, and duplicate reads.
