### ISSUE TITLE
question: `--by` and quantized output

### ISSUE THREAD

**Issue by matthdsm** [brentp/mosdepth#193]
Hi Brent

Is the quantized output supposed to be filtered by the regions given in `--by` ? I'm trying to create "callable" loci within a set ROI for exome analysis.

Thanks
M

**Comment by brentp** [comment]
Hi Matthias, no, it still outputs the full genome. But it *should* be simple to do a bedtools intersect with target regions afterward.

**Comment by matthdsm** [comment]
guessed something like that. Thanks for the reply!

Matthias
