### ISSUE TITLE
Exclusion of reads with -F flag

### ISSUE THREAD

**Issue by aklein-705** [brentp/mosdepth#194]
I see the default for the F flag option has a default value of 1796. I was wondering if when excluding the PCR or optical duplicates, does mosdepth retain one of these duplicates that is then used in the coverage calculation? Or all all of them excluded? Thank you!

**Comment by brentp** [comment]
mosdepth will exclude anything marked with the given flag(s). Usually, the software that mark duplicates will leave a single read or template that is not marked.

**Comment by aklein-705** [comment]
Thanks so much for the quick reply!
