### ISSUE TITLE
[hts-nim] error adding to csi index

### ISSUE THREAD

**Issue by nylander** [brentp/mosdepth#195]
Hi,
I'm receiving an error saying:

```
$ mosdepth -b ../../../../reference/ref.fasta.bed -t 2 -n -x prefix PS-A1.bam
[E::hts_idx_check_range] Region 977930..1679516 cannot be stored in a csi index with min_shift = 14, n_lvls = 2. Try using min_shift = 14, n_lvls >= 3
[hts-nim] error adding to csi index
```
Which leaves me clueless on where to start debugging.
Should I check the format of my bed file (it's supposed to reflect the intervals for each chromosome)? First lines:
```
VACF01000001.1  0       977930
VACF01000002.1  977930  1679516
VACF01000003.1  1679516 2235559
VACF01000004.1  2235559 2496722
VACF01000005.1  2496722 2609266
```
Thanks
/Johan

**Comment by brentp** [comment]
Hi Johan, Can you share theheader of your bam file?

**Comment by nylander** [comment]
Dear @brentp ,
Sure. I try by attaching a file to this comment. Output from command `samtools view -H PS-A1.bam > PS-A1.bam.header.txt`.
[PS-A1.bam.header.txt](https://github.com/brentp/mosdepth/files/10548542/PS-A1.bam.header.txt)

**Comment by brentp** [comment]
So your bam header has this:
```
@SQ	SN:VACF01000002.1	LN:701586
```
and your bed file has this:
```
VACF01000002.1  977930  1679516
```
so your bed is querying off the end of the chromosome. It certainly would be nice if mosdepth handled this better, but this is the cause of your error. 
Your bed file:
```
VACF01000001.1  0       977930
VACF01000002.1  977930  1679516
VACF01000003.1  1679516 2235559
VACF01000004.1  2235559 2496722
VACF01000005.1  2496722 2609266
```
is incrementing each chromosome to start and the end of the other. Each chrom should start at 0 and end at SN from the bam tag.

**Comment by nylander** [comment]
Thank you so much @brentp for your quick reply. I will try to transform the bed file I received to follow your specifications (but "end at LN")!
Closing this issue now
Cheers
Johan
