### ISSUE TITLE
"SIGSEGV: Illegal storage access. (Attempt to read from nil?)" when using bed file

### ISSUE THREAD

**Issue by GACGAMA** [brentp/mosdepth#197]
Hello!
I have a BED file (without headers) containing all chromossomes names from my reference and the start / end (0-based)
![image](https://user-images.githubusercontent.com/30120425/225497483-7a29d0d4-e26b-492b-81e0-257ab24f9f59.png)

When using

`mosdepth --by /data1/references/GCF_000001405.40_GRCh38.p14_genomic_clean.bed  /data1/analises/mosdepth/1995 /data1/analises/bam/1995.bam`

I get:
"SIGSEGV: Illegal storage access. (Attempt to read from nil?)" 

When using

`mosdepth --by (anynumber)  /data1/analises/mosdepth/1995 /data1/analises/bam/1995.bam`
Or
`mosdepth /data1/analises/mosdepth/1995 /data1/analises/bam/1995.bam`

It just works. 

Any ideas?

**Comment by brentp** [comment]
can you show the header from your bam file with the SN for the chroms in your bed file above?

**Comment by GACGAMA** [comment]
[header_BAM.txt](https://github.com/brentp/mosdepth/files/10986695/header_BAM.txt)
This is the bam header as obtained by samtools view -H 1955.bam > header_BAM.txt

**Comment by brentp** [comment]
can you run with this binary and show the error? Just gunzip and chmod +x and run
[mosdepth_debug.gz](https://github.com/brentp/mosdepth/files/10991565/mosdepth_debug.gz)

**Comment by GACGAMA** [comment]
I got the following error:

[mosdepth] WARNING: built in debug mode; will be slow
/home/brentp/src/mosdepth/mosdepth.nim(878) mosdepth
/home/brentp/src/mosdepth/mosdepth.nim(647) main
/nim-1.6.6/lib/system.nim(2622) []
/nim-1.6.6/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: index 248956423 not in 0 .. 248956422 [IndexDefect]

I suppose it has something to do with my bed file being a 0-based file?

**Comment by brentp** [comment]
ok. Thanks for following up. I push a fix that prevents an IndexDefect in this scenario.
