### ISSUE TITLE
High memory usage for very small BAM files

### ISSUE THREAD

**Issue by slazicoicr** [brentp/mosdepth#200]
We have experienced running out of memory failures with small BAM files. 

I was able to reproduce it using [bam_test.zip](https://github.com/brentp/mosdepth/files/11434883/del_sub.zip) file, which includes 46 properly paired reads.

When running it on a node with 4GB of memory with the command `mosdepth -x -n -t 3 bamqc del_sub.bam`, the command gets killed due to high memory usage. 8GB sometimes works, but we've seen it fail as well with small BAM files.

What's strange is that we don't see this out of memory errors with large BAM files.

**Comment by brentp** [comment]
This is expected. The memory use in mosdepth is not dependent on the number of reads. It is only dependent on the size of the largest chromosome. It pre-allocates an array the length of the chromosome where each entry is 4 bytes.
