### ISSUE TITLE
question about WGS data

### ISSUE THREAD

**Issue by crazysummerW** [brentp/mosdepth#203]
Hi,
I am performing quality control analysis on WGS data, and I have a few questions.  
1. How can I obtain statistics similar to gatk CollectWgsMetrics? 
   Such as, MEAN_COVERAGE, PCT_5X, PCT_10X, PCT_20X, PCT_30X...
2. Is this tool suitable for PacBio revio WGS data?

Looking forward to your reply.
Thanks.

**Comment by brentp** [comment]
Hi,
You can use the .dist.txt output to get the percentile coverage and the .stats file will tell you the mean.
You can see more about the dist(ribution).txt file [here](https://github.com/brentp/mosdepth#distribution-output)
So you can run mosdepth with default parameters to get those outputs.

And yes, this will work well for revio.
Please let me know any other questions.
-Brent

**Comment by crazysummerW** [comment]
Hi, @brentp 
Thanks for your reply.
My cmd:
`mosdepth -t 12 -n --fast-mode test.out test.hifi_reads_aligned.bam`
The result file:
.dist.txt
![image](https://github.com/brentp/mosdepth/assets/70870741/06c8311b-7025-45b7-a7c9-75a6b11e3a5f)
I have some questions:
   1. Is the second column representing sequencing depth? The third column has a number of zero values. Is this result file correct?
   2. Could you please provide an example on how to calculate coverage at different depths? 

Looking forward to your reply.
Thanks.
