### ISSUE TITLE
Filter by alignment score (AS) and number of mismatches (NM) [feature request]

### ISSUE THREAD

**Issue by sjackman** [brentp/mosdepth#21]
I'd like to filter out reads with an alignment score below a threshold (< 100 for example) and number of mismatches above a threshold (≥ 5 for example). Alternatively, I'd also appreciate your suggesting a tool that's fast for such filtering that I could then pipe into mosdepth. Thanks!

**Comment by brentp** [comment]
you mean you want to filter on tags? `AS` and `NM`? with mosdepth, you can directly filter on qual, but not on tags. you can do this with sambamba view: https://github.com/lomereiter/sambamba/wiki/%5Bsambamba-view%5D-Filter-expression-syntax

This would be also a nice tool to build on top of hts-nim, using [kexpr-nim](https://github.com/brentp/kexpr-nim)

**Comment by sjackman** [comment]
Thanks, Brent. Yep, filter on the `AS` and `NM` tags. I'll try out Sambamba. Feel free to close this issue if you like.

**Comment by brentp** [comment]
cool. I think this is best handled by an external tool but I'll leave this open for now to remind me to revisit seeing how much work it would be to build something like this with the same machinery.

**Comment by sjackman** [comment]
Although it could be generalized to arbitrary tags, the three that I typically filter on are MAPQ, AS, and NM.

**Comment by brentp** [comment]
this is implemented in: https://github.com/brentp/hts-nim-tools

**Comment by sjackman** [comment]
Thanks! I'll check it out.
