### ISSUE TITLE
funny global depth of coverage plot

### ISSUE THREAD

**Issue by prasundutta87** [brentp/mosdepth#210]
Hi,

I calculated coverage statistics using mosdepth and then combined the outputs using MultiQC. The dataset is ONT long reads. The cumulative depth of coverage plot look okay for most samples, but one sample looks funny and step-wise (sample 3 resequenced)? Alignment was done using minmap2 for all samples. This does not seem to be mosdepth dependent as this was also observed when Qualimap was run and combined using MultiQC, not it seems to be chemistry or analysis pipeline dependent as everything was same for all samples. Any help/pointers from you will be very helpful.

![image](https://github.com/brentp/mosdepth/assets/25484608/86bd1861-e582-423b-afdb-406868f7bfa0)

Regards,
Prasun

**Comment by brentp** [comment]
That *is* odd. Nothing comes to mind. I guess you could do a plot with indexcov and see the coverage across the genome.
