### ISSUE TITLE
[Question]: mosdepth 0.3.5 in bioconda/docker

### ISSUE THREAD

**Issue by tamuanand** [brentp/mosdepth#212]
Hi @brentp 

I was wondering if 0.3.5 would be made available on bioconda and/or dockerhub

https://github.com/brentp/mosdepth/releases/tag/v0.3.5

Thanks in advance

**Comment by pdiakumis** [comment]
The v0.3.5 conda pkg + biocontainer should be up in a couple hours (I think)
https://github.com/bioconda/bioconda-recipes/pull/43500

**Comment by tamuanand** [comment]
Thanks @pdiakumis
