### ISSUE TITLE
MAPQ 0 reads discarded even if --mapq 0 used

### ISSUE THREAD

**Issue by valeandri** [brentp/mosdepth#215]
Hello,

I am testing mosdepth looking for a faster alternative to bedtools genomecov.

Looking into the generated tracks, I noticed that mosdepth discards MAPQ 0 reads even if the --mapq filter shoud allow to count them (default value is 0). Reading the documentation, this should not be the case. Is it a bug or a known behavior?

Version of the tools used:
bedtools v2.27.1
mosdepth 0.3.5

Command used:
```
bedtools genomecov -ibam $in_bam -bg > $out_genomecov
mosdepth $prefix $in_bam
```

IGV visualization of the tracks:
![Screenshot from 2023-11-03 11-56-36](https://github.com/brentp/mosdepth/assets/63858464/96296db0-f386-4a1c-a55d-b3eeeaa72183)

Thanks,
Valentina

**Comment by brentp** [comment]
The read you have pulled up in the IGV window is marked as `secondary`. If you want to count secondary reads, you can adjust the `--flag` argument.
The code in mosdepth checks:
```
  if int(rec.mapping_quality) < mapq: continue
```
so it will work as you expect.

**Comment by valeandri** [comment]
Thanks a lot!!
