### ISSUE TITLE
Empty per-base output file if all reads in input BAM are unmapped

### ISSUE THREAD

**Issue by julibeg** [brentp/mosdepth#216]
When running `mosdepth` on a BAM file containing only unmapped reads, I would expect to get a per-base depth file with 
```
ref_id    0       X       0
```
with `X` being the length of the reference. Instead, `*.per-base.bed.gz` is empty.

To reproduce, run the following script
```
#!/bin/bash

(
    echo '>ref'
    echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
) > ref.fa

(
    echo '>read1'
    echo CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    echo '>read2'
    echo GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
) > reads.fa

bwa index ref.fa
bwa mem ref.fa reads.fa | samtools sort -o sorted.bam
samtools index sorted.bam
mosdepth depth sorted.bam

# depth.per-base.bed.gz is empty
```

**Comment by brentp** [comment]
Hi, per-base output is only reported for non-zero depth. This is by design.

**Comment by julibeg** [comment]
Hi and many thanks for the quick reply! Could you please explain your comment a little further?
If I run mosdepth on the following dummy SAM file
```
@HD	VN:1.6	SO:coordinate
@SQ	SN:ref	LN:47
seq	0	ref	10	60	38M	*	0	0	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	*	NM:i:0	MD:Z:38	AS:i:38	XS:i:0
```

I get this as per-base output:
```
$ zcat depth.per-base.bed.gz 
ref     0       9       0
ref     9       47      1
```

From your comment I wouldn't expect the first line to be there.

**Comment by brentp** [comment]
Hah, you got me. It's been a while since I really was deep into the mosdepth code.
Will you give this binary a try and let me know if it resolves your issue?


[Uploading mosdepth_dev.gz…]()

**Comment by julibeg** [comment]
Nice, the binary indeed gives the expected output (at least for the toy example above):
```
$ zcat depth_dev.per-base.bed.gz 
ref     0       47      0
```

**Comment by brentp** [comment]
thank you. I made a new release that incorporates this change.
