### ISSUE TITLE
Insert size of 0

### ISSUE THREAD

**Issue by LudvigOlsen** [brentp/mosdepth#217]
Hi @brentp ,

I have a dataset where the insert size field is always 0, why no fragments are used when filtering on fragment size. I'm wondering if that case needs to be handled in the size filtering? E.g. if the insert size is 0, we calculate it from the positions instead?

**Comment by LudvigOlsen** [comment]
I think we will try to fix the bam files instead. Seems like a better approach. Leaving the issue open in case you want to think about it, but feel free to close it.

**Comment by brentp** [comment]
Hi @LudvigOlsen , can you clarify what you're trying to do? If they all have an insert size of 0, then you either filter all or None with the --min/--max-frag-len params?

**Comment by LudvigOlsen** [comment]
Hi Brentp,

The true fragment length was not 0, so I wanted to calculate the real lengths for the filtering (from the reads). 
But I fixed the BAM files instead, which is most likely the solution that type of problem.
