### ISSUE TITLE
sequencing depth after deduplication

### ISSUE THREAD

**Issue by pickpingk** [brentp/mosdepth#218]
Hello,
I would like to ask, if I input a bam file with marked duplicates, can I get the original sequencing depth and the sequencing depth after deduplication? If not, how can I get the sequencing depth after deduplication?

**Comment by brentp** [comment]
Hi, you can modify :
```
  -F --flag <FLAG>                  exclude reads with any of the bits in FLAG set [default: 1796]
```
to exclude/include duplicates. By default they are excluded, you can include with:
```
-F 772
```
see more here: https://broadinstitute.github.io/picard/explain-flags.html

**Comment by pickpingk** [comment]
Thank you for your reply;
I have one more question. Can I get both results at the same time? Sequencing depth of raw data and deduplication sequencing depth

**Comment by brentp** [comment]
No, you'll have to run mosdepth twice.

**Comment by pickpingk** [comment]
thank you for your replay! have a nice day.
