### ISSUE TITLE
Sort error

### ISSUE THREAD

**Issue by kellogg76** [brentp/mosdepth#22]
I'm trying to use your mosdepth tool to get a feel for what was covered in a recent Illumina exome that I ran, however I keep getting an error that my bam isn't sorted when i'm pretty sure it is.

This is the command I'm using to run mosdepth :-

mosdepth --by ccds.bed 2450 ~/2450.recalibrated.sorted.bam

And this is the error I receive :-

[hts-nim] starts out of order for:2450.regions.bed.gz in:1    8384339    8384836    CCDS30577.1_exon_0_50_1_8384390_f    47.71
[E::hts_idx_push] Unsorted positions on sequence #1: 67208705 followed by 8384339
[hts-nim] error adding to csi index

**Comment by brentp** [comment]
I pushed a fix for this that allows the intervals to --by to be specified out of order. this will be available in the next release. meanwhile, you can use;
```
mosdepth --by <(sort -k1,1 -k2,2n ccds.bed) 2450 ~/2450.recalibrated.sorted.bam
```
thanks for reporting.
