### ISSUE TITLE
Write out mean/median mapq

### ISSUE THREAD

**Issue by holtgrewe** [brentp/mosdepth#221]
Thank you for the awesome tool. For some applications such as filtering cnvs, the average mapping quality within a window would be useful.

Would this be something to consider for inclusion in mosdepth?

**Comment by brentp** [comment]
Hi,
I see the utility, but this for me is clearly outside the scope of mosdepth. 
I think that, given a set of SVs, it would be quite quick to calculate this in a custom script/program.
