### ISSUE TITLE
Soft and hard clipped bases

### ISSUE THREAD

**Issue by ezherman** [brentp/mosdepth#228]
Hi, I just wanted to double-check that `mosdepth` does not include soft and hard clipped bases in calculating coverage depth. I.e., if bases are clipped in the alignment, they do not add to coverage depth. I noticed [here](https://github.com/brentp/mosdepth/blob/388d2e0d5739b894ed9e0e82cfd771d710cf4bb3/CHANGES.md?plain=1#L67) that `mosdepth` is said to "consider" soft and hard-clipped bases, but I was unsure how to interpret that. 

Thanks!

**Comment by brentp** [comment]
Hi, `mosdepth` does *not* count soft or hard clipped bases.

**Comment by ezherman** [comment]
Great, thank you!

**Comment by brentp** [comment]
in fast mode, cigar events such as insertions or deletions are not considered (but soft-clips and hard clips are still not counted).

**Comment by ezherman** [comment]
Gotcha! But how about when *not* running fast mode? Am I right to think that if we have `50M4I50M`:
- In fast mode, 104 bases from the start position would be counted as covered.
- Not in fast mode, 100 bases from the start position would be counted as covered.

**Comment by brentp** [comment]
no, in both cases, 100 bases of the reference are covered. 
Insertions don't matter for coverage (I should have noted that above).

The difference would be for `50M4D50M`. Fast mode would cover 104 bases, default would be 50 bases, then gap, then 50 bases covered.

**Comment by ezherman** [comment]
Understood, thank you @brentp!
