### ISSUE TITLE
ENH: output per-region counts (not means) for --by

### ISSUE THREAD

**Issue by brentp** [brentp/mosdepth#23]
currently, the output for each region specified via --by is the mean per-base coverage of the region. This is because that's what the machinery in `mosdepth` facilitates.

For many use-cases, users want the actual count of reads that overlap an interval. I have stubbed out  a way to do this that is fast enough to incorporate using [lapper](https://github.com/brentp/nim-lapper).

On my test-case with an exome, and a --by file with  1,195,764 intervals, this takes the run-time for mosdepth from 130 seconds to 140 seconds and user-time with 2 decompression threads from 50 seconds to 60 seconds. I think this is acceptable given the utility and the fact that `samtools bedcov` takes ~33 minutes on the same bam and bed file. So, this is **2:20 for mosdepth** and **33:30 for `samtools bedcov`**

With a bed file of 10 million 300-base windows (to simulate --by 300 because I haven't implemented this for integer window yet), the user time goes only up to 80 seconds for the same (exome bam). 

I would like to get feedback from @chapmanb and anyone else interested on how to expose this. Should this replace the output for `$prefix.regions.bed.gz` ? Or should it be a new file `$prefix.region-counts.bed.gz`? I would prefer to replace the output in `$prefix.regions.bed.gz` but are there any common use-cases for the current mean output?

note that this would leave all other output files unchanged.

**Comment by chapmanb** [comment]
Brent -- wow, thanks for this work. ccing in @vladsaveliev in case he has comments as well.

Right now we use the regions mean output as the direct input into CNV calling. It generates target and antitarget mean coverage by bins, but then we immediately turn this into log2 scaled output `cnn` output:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/structural/regions.py#L164

so we could calculate the mean as `count / (end - start)` at this point and deal with the changed region files, so I'm open to changing the behavior to avoid having extra files.

Thanks again for working on this.

**Comment by brentp** [comment]
thanks for the feedback. Seems like this won't affect you except that the value will be slightly more accurate. I think I can squeeze out a bit more performance and figure out what to do with overlapping pairs and after that I'll evaluate the differences--I suspect that will be a few percent.

@vladsaveliev let me know if you have any additional input.

**Comment by vladsaveliev** [comment]
Brent, Brad,

The issue I see is that `count * read_len / (end - start)` doesn't actually return the average coverage because of the reads partially overlapping the region. For small intervals the difference might be significant. I ran into this being an issue when I was integrating Seq2C which relies on average coverages for input intervals. We also rely on interval coverages to calculate the total average sample depth: https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/coverage.py#L179 which might be inaccurate with counts.

**Comment by brentp** [comment]
@vladsaveliev that's a good point. I hadn't thought of that. so it seems at least that we should keep reporting the per-base average in `$prefix.regions.bed.gz`, then the question is if there's utility in having the counts. As it is (sorta) implemented, mosdepth would report the count of overlaps, so with adjacent regions, a single alignment could contribute to multiple regions. I'm not sure what's the most useful thing to report here.

@etal would you mind weighing in here? what's a useful output to have for CNV stuff? Is the count of overlapping reads actually useful to supplement average per-base coverage in the region?

**Comment by etal** [comment]
For CNVkit's .cnn files the mean per-base coverage in each region is perfect as it is, I think. Since CNVkit's coverage bins are often adjacent, counting reads instead of bases results in double-counting (or more, if the bins are skinny). I've tried that the slow way in the past and the accuracy of calls was not as good.

**Comment by chapmanb** [comment]
Eric and Vlad -- thanks for the thoughts, it does sound like keeping the averages is the way to go.

Brent -- the initial motivation for counts from my side was to replace `samtools view -c` over regions. It currently doesn't support index lookups with BED files, instead iterating over the whole file. As a workaround I have to block up the regions on the command line and sum them together; it's pretty ugly and slow. I use this to get total count so would be fine with that output, or summing them by regions also works great. So it would be useful independently of CNV region binning if it's reasonable to push through to a final implementation.

Thanks again for all this work and discussion.

**Comment by brentp** [comment]
I will wait for any further discussion and let this marinate, but based on what I've seen so far, my inclination is to leave this out of `mosdepth`.
I am planning to write up [hts-nim](https://github.com/brentp/hts-nim) and to extend its functionality to include `bcf`/`vcf` and a few example applications. I think this will make a nice example application for that repo along with the filtering app in brentp/mosdepth#21. (and not to derail this issue, but I also welcome any other needed tools for that. it's quite easy to "script" up a simple tool that's often faster than a C-program with these nim bindings)

**Comment by brentp** [comment]
this is implemented in https://github.com/brentp/hts-nim-tools
