### ISSUE TITLE
feat: per base in BED regions only?

### ISSUE THREAD

**Issue by cademirch** [brentp/mosdepth#233]
Hi Brent,

Thanks for making such a great tool!

I've been using `-by` and I am curious if it would be possible to output per-base depth in the BED regions? 

My current workflow is to output the per-base depth then subset it to my regions of interest. My thought is that doing the above would maybe give some performance boost since mosdepth wont have to write every base. 

Let me know your thoughts, if you're open to a PR I can take a look at implementing this. 

Best,
Cade

**Comment by brentp** [comment]
Hi Cade, it's a reasonable request and you are right that it would increase performance. For the sake of simplicity of the tool, I don't intend to implement.
If your --by file has relatively few intervals, then you could use tabix on the bed.gz since it comes out indexed.

**Comment by cademirch** [comment]
Makes sense, thanks for the quick response!

**Comment by cademirch** [comment]
Getting `[W::tbx_parse1] Coordinate <= 0 detected. Did you forget to use the -0 option?` when querying the per-base bed. Not sure if this warning matters, but it goes away if I recreate the index using the `-0`
