### ISSUE TITLE
plot-dist.py legend

### ISSUE THREAD

**Issue by WWz33** [brentp/mosdepth#238]
![image](https://github.com/user-attachments/assets/f528c0fb-3053-4acb-bb77-e3d3b1414dba)

Change the x coordinate
```
        legend: {
            x: 1.1,
            y: 0.1
        },
```
![image](https://github.com/user-attachments/assets/9a2bce08-295b-4f0d-8f1e-a6761e663461)

**Comment by brentp** [comment]
hi, feel free to do this! plot-dist.py is provided as a starting point. in many cases, it's better to have it in lower left, but not in your case.

**Comment by WWz33** [comment]
Hi,brentp!

Thanks for your reply

Best!
