### ISSUE TITLE
mosdepth on single bam vs chunks of bam

### ISSUE THREAD

**Issue by reshu23** [brentp/mosdepth#239]
Dear Team,
If I use mosdepth on a single bam/cram file for bin size = 1000 or I split same bam file in to chunks and I calculate mosdepth coverage with bin size=1000 on every chunk, will it affect the result? Should I expect same result in both situation?

**Comment by brentp** [comment]
you should get the same result, but it will be more efficient to keep a single bam and run mosdepth once.
