### ISSUE TITLE
Mosdepth on Windows OS

### ISSUE THREAD

**Issue by unikzforce** [brentp/mosdepth#24]
I've just managed to compile htslib and create htslib.dll on MSYS2/MinGW stack on windows.
is it possible to compile this beauty you just created here for windows. 
would you please help me?

**Comment by brentp** [comment]
can you use a single issue for all this? there are 2 issues in hts-nim and now this one.

You can look at https://github.com/brentp/mosdepth/blob/master/scripts/install.sh

to see how I install this. If you have nim and nimble installed, then it would be:

`cd hts-nim && nimble install`

and `cd mosdepth && nim c -d:release mosdepth.nim`

**Comment by unikzforce** [comment]
sorry for scattered issues

**Comment by unikzforce** [comment]
in windows "aux" is a reserved word, a file name should not start with aux
so hts/aux.nim creates errors, and nimble cannot proceed.

**Comment by unikzforce** [comment]
after renaming aux to naux ---> nimble installed hts-nim successfuly

**Comment by brentp** [comment]
thanks for figuring this out. I am restructuring the hts-nim package now and will rename that file.

**Comment by nilsj9** [comment]
@unikzforce I've managed to compile htslib on MSYS2, but still keep getting the error 'could not load: libhts.dll'. How did you create this file? Would you help me please?
