### ISSUE TITLE
Range of Per-base Coverage

### ISSUE THREAD

**Issue by DarioS** [brentp/mosdepth#241]
[International Journal of Cancer](https://onlinelibrary.wiley.com/page/journal/10970215/homepage/forauthors.html) has an annoying requirement for all submissions. May `mosdepth` output it?

![image](https://github.com/user-attachments/assets/c928d5ca-b120-4ee8-a586-419238c3624d)

I would hate to have to calculate it for 100× whole-genome sequencing data in R using the BED file as input.

**Comment by brentp** [comment]
this is a bit outside the scope of mosdepth, but did you look at the summary.txt file? it provides a lot of this.

**Comment by DarioS** [comment]
Ah, indeed it does, in `min` and `max` column. For the benefit of others,

Total number of Sequenced Reads: Calculated from FASTQ file before alignment.
Number of Covered Bases, Coverage ≥ 10 :  `--thresholds 1, 10`
Median Coverage: `--median`
