### ISSUE TITLE
Build sfi index in d4 files?

### ISSUE THREAD

**Issue by cademirch** [brentp/mosdepth#243]
Hi @brentp, would you be open to this? It seems like the d4 bindings don't have an api for building the index, but it should be fairly simple to do, its available to the python bindings: https://github.com/38/d4-format/blob/480e0a36a453fd3ec40b6768458f8892e6f36510/pyd4/src/builder.rs#L129-L144. 

I'd be happy to work on implementing this, but want to check if you're open to it first. Would require changes in d4-nim too presumably

**Comment by brentp** [comment]
hi @cademirch , yes, I'm open to it. If you have any questions on d4-nim, I'll try to answer.

**Comment by cademirch** [comment]
Sweet. Opened up prs on d4-format and d4-nim for this. Should building the index be an option in mosdepth? Or just build it by default? It seems like the sfi index is tiny so maybe can just be built by default?

**Comment by brentp** [comment]
let's make it on by default

**Comment by brentp** [comment]
I'll make a new release that bumps with your changes to d4-nim and should therefore allow this.

**Comment by cademirch** [comment]
awesome. thank you @brentp!

**Comment by cademirch** [comment]
am i missing something or is there no call to the index function in https://github.com/brentp/mosdepth/commit/d1b19aa5191958c2595536072fe99ee75509dd98?

**Comment by brentp** [comment]
doh! yeah, I am on it.

**Comment by brentp** [comment]
I pushed another commit and overwrite v0.3.10. working on getting all my stuff updated so I can make a static binary and proper release.

**Comment by cademirch** [comment]
great! thank you very much

**Comment by brentp** [comment]
done. thanks again: https://github.com/brentp/mosdepth/releases/tag/v0.3.10
please let me know any other problems.
