### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by wresch** [brentp/mosdepth#27]
I built the current head of the repo (e0131e3) on Centos 6.9 with the head of the nim repo (that was the only combination i was able to make work - had to use nim head b/c c2nim would not build on 0.17.2. had to use mosdepth head b/c the 0.2.0 release failed with a type error `mosdepth.nim(362, 10) Error: type mismatch: got (seq[int64], int64, int literal(0))`. could not use prebuilt binary b/c of old glibc). I'm using RUNPATHs in the executable instead of LD_LIBRARY_PATH for pcre and htslib (set with patchelf).  I'm testing with 1000g data and for the most part tests run fine except for intermittent segfaults:

```shell
$ mosdepth -n --by 500 -t3 HG00096_WGS \
    data/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

The bam file is from `ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/phase3/data/HG00096/alignment/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam`.

The segfaults seem to be happening only when using non-default values for the bam decompression threads (`-t`) but even then a couple of (identical) runs did finish without a segfault - i.e. it does not occur in 100% of runs.

**Comment by brentp** [comment]
hmm, thanks for reporting. I'm not sure off-hand.
since you're building on your own, could you build without -d:release (you can use -d:debug) and then let me know the full error output?

if the debug build is too slow, you can use `nim c -d:release --nilChecks:on --stackTrace:on`

you might also need to update hts-nim as I changed the structure of that in the last couple of weeks.

finally, did you try the binary from bioconda? this is built with an older libc that works on most machines.

**Comment by brentp** [comment]
and one more thing I thought of is to make sure you have the latest htslib release

**Comment by wresch** [comment]
- i never got a SIGSEGV when running against an exome with a capture bed, even when multithreading
- compiled with `-d:debug`, `nim-hts@0.1.5`, `samtools=1.6`: no SIGSEGV
- compiled with `-d:release --nilChecks:on --stackTrace:on`, `nim-hts@0.1.5`, `samtools=1.6`:
    ```shell
    $ bam=data/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
    $ ./mosdepth -t3 -n --by 500 $bam
    Traceback (most recent call last)
    mosdepth.nim             mosdepth
    mosdepth.nim             main
    mosdepth.nim             coverage
    mosdepth.nim             init
    system.nim               newSeq
    gc.nim                   newSeq
    gc.nim                   newObj
    alloc.nim                rawAlloc
    alloc.nim                getBigChunk
    alloc.nim                incl
    alloc.nim                intSetPut
    alloc.nim                intSetGet
    SIGSEGV: Illegal storage access. (Attempt to read from nil?)
    ```
- bioconda executable: no SIGSEGV
- `nim-hts@#head`: i compiled against the head of the hts repo but the resulting executable had the same checksum as the one compiled against nim-hts 0.1.5, so i didn't run any tests

Maybe that's a nim compiler or runtime issue, not a mosdepth issue? Either way, I'll use the bioconda executable for now so not a high priority at all.

**Comment by brentp** [comment]
thanks for checking.
can you add `--lineDir:on` to the compile args? that should give the exact line number along with the traceback. then I can figure out where this is coming from.

make sure you have nim-hts from github as I have been messing with that without bumping the version. I'll start doing that now since more people seem to be building their own binaries.

**Comment by wresch** [comment]
nim is kind of new to me which is part of the reason i decided to build from source to begin with. I did a `nimble install hts@#head`  which reported

```
Downloading https://github.com/brentp/hts-nim using git
  Verifying dependencies for hts@#head
      Info: Dependency on c2nim@>= 0.9.10 already satisfied
   Warning: [...snip...]
installation by adding `skipDirs = @["testsuite"]` to the .nimble file.
  Verifying dependencies for c2nim@0.9.13
      Info: Dependency on compiler@>= 0.16.0 already satisfied
  Verifying dependencies for compiler@#head
 Installing hts@#head
   Success: hts installed successfully.
```

and `nimble list --installed` shows

```
c2nim  [0.9.13]  
compiler  [#head]
docopt  [0.6.5]  
hts  [#head]     
```
Is that not the head of the hts repo? Should i clone manually and install from the clone?

**Comment by brentp** [comment]
That should be ok for head

**Comment by wresch** [comment]
`--lineDir:on` didn't make a difference. With `--lineTrace:on` I got:

```
Traceback (most recent call last)
mosdepth.nim(689)        mosdepth
mosdepth.nim(525)        main
mosdepth.nim(248)        coverage
mosdepth.nim(221)        init
system.nim(742)          newSeq
gc.nim(503)              newSeq
gc.nim(496)              newObj
alloc.nim(682)           rawAlloc
alloc.nim(594)           getBigChunk
alloc.nim(337)           incl
alloc.nim(321)           intSetPut
alloc.nim(316)           intSetGet
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by brentp** [comment]
I can recreate locally with the bam you linked to. I'll get this fixed for the next release.

**Comment by wresch** [comment]
Great. Thanks.

**Comment by brentp** [comment]
I was able to get around this using choosenim.
Basically:

```
curl https://nim-lang.org/choosenim/init.sh -sSf | sh
PATH=$HOME/.nimble/bin:$PATH
nimble install -y
nim c -d:release mosdepth.nim
```

**Comment by brentp** [comment]
In c751c61, I made a build script that you should be able to run on an old machine (or modify as needed) and there's a hbb.sh script to build inside of holy-build-box. I will use this in future releases to make a binary for systems with older libc's.

**Comment by brentp** [comment]
The latest binary is build using holy-build box which should make it work on older systems. please reopen if you have more issues.

**Comment by wresch** [comment]
Hi Brent,

thanks for the time you spent on this issue!

W

**Comment by Biojenifer** [comment]
Hi!

I am getting this error with the bed file to calculate coverage by regions:

`[E::hts_open_format]` Failed to open file /mnt/netapp2/databases/regions.bed
SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

But I think its cause is different from that of the post.

My bed file looks like that:

1       31999332        32000052        1p35.2
1       32000313        32001153        1p35.2
1       32001173        32001557        1p35.2
1       32001668        32002340        1p35.2
1       32002630        32003254        1p35.2

Do you know what is the problem?
Thanks!
