### ISSUE TITLE
Replacing usage of sambamba depth with mosdepth

### ISSUE THREAD

**Issue by chapmanb** [brentp/mosdepth#3]
Brent;
mosdepth looks awesome and we're looking into replacing depth calculation code in bcbio with it. As a first pass, we'd like to replace our usage of `sambamba depth` for QC and coverage calculations (and then hope to tackle goleft depth and other usage). This is work that @vladsaveliev did in bcbio so cc'ing him in for the discussion as well.

We use `sambamba depth` in two ways: calculation of average depth in regions and depth at thresholds. Standard mosdepth usage can replace the first and `--distribution` can replace the second. There are just a couple of usage differences I wanted to ask about:

- We currently limit depth calculations based on SAM flags, removing reads with unmapped, mate unmapped, not primary, failedQC and duplicate flags set. Is it possible to add this for restricting the mosdepth calculations?

- `sambamba depth` adds the BED name column, the 4th field, into the output. This is handy for aggregating depth calculations by gene names. Would it be possible to include that in the mosdepth output? Or would we be better doing this with some combination of `bedtools intersect` and awk magic coming out?

Thanks again for mosdepth; brilliant work.

**Comment by brentp** [comment]
Hi Brad, would be great to get bcbio using mosdepth. As you'll see from the recently added timings in the README, you should see a nice speed improvement over sambamba. And it will much reduce CPU and disk load from goleft depth.

I couple of points/ todo's for me:

The default filtered are: `BAM_FUNMAP`, `BAM_FQCFAIL`, `BAM_FDUP`, `BAM_FSECONDARY`. I'll 
+ [ ] make a command-line flag `-F` with that as the default that you can send an integer flag that covers what you want to exclude.

For the name column, I assume you mean `sambamba depth`, not `samtools depth` ? and you mean that it sends the 4th field of the input regions to the output? I'll:
+ [ ] see about adding this if it doesn't add any overhead--which I don't think it will.

One issue I see is it might be hard to get a binary out that will work on all platforms (I haven't heard much about the one that I posted). I haven't tried setting this up on bioconda yet but this will be something we'll have to address before you rely on it wholesale.

That said, once I implement the above points, I think we can resolve the installation. I'll ping this issue when there's a new release with those added or for clarification.

**Comment by brentp** [comment]
I see someone has already added this to bioconda. That should make it easy to test how widely usable the binary is until I figure out linking statically to htslib

**Comment by chapmanb** [comment]
Brent -- thanks so much for looking at this. It sounds like we'll be good with the default flags but it would be nice to be able to tweak as well. Sorry and I did mean `sambamba` -- I corrected the typo above to not be so confusing. Passing along the 4th field of the input BED would be perfect, thank you.

I have a couple of small fixes to the bioconda package (make it executable, be sure we pin to the bioconda htslib version) but it did work out of the box for me on a Ubuntu machine after those. I'll push those updates, along with 0.1.2 binary. I don't really understand how the htslib magic works -- `ldd` doesn't appear to show the linking -- but conda appears to resolve it correctly to the installed htslib. If I just download the binary it doesn't work but after the magic conda treatment it's fine. So I think we'll be good with that package but happy to hear if others find issues.

Thanks again for all the help.

**Comment by brentp** [comment]
hold off and I'll have a 0.1.3 binary in ~20 minutes with the above features implemented so you can test it fully.

**Comment by chapmanb** [comment]
Wow thanks. I'll plan to update the package tomorrow (I've got other fixes to packages to do) so no big rush, thank you again for looking at it.

**Comment by brentp** [comment]
for the name column. do you have a preference on order? I currently have:

chrom,start,end,depth,name

but can do:

chrom,start,end,name,depth

if you prefer.

**Comment by chapmanb** [comment]
No preference from me. `sambamba depth` puts the name first so you could do that to be consistent with what it does.

**Comment by vladsaveliev** [comment]
Brent, thanks so much for doing that, it's so great to boost coverage calculation in bcbio.

BED file is not well standardized, and it can easily have any number of columns. Becide 4-col files, common cases that I've seen in production are 6 columns with strand and exon numbers, and 8 columns with additional coordinates of amplicons. Sambamba depth keeps all original columns, with a header like `chrom,start,end,F1,F2,F3,...,readCount,meanCoverage,sampleName`. It would be great to keep all columns as well in mosdepth to avoid additional postprocessing.

**Comment by brentp** [comment]
ok. new release it out with just the name column transferred. if we need more, let me know and we'll figure it out. thanks guys.
