### ISSUE TITLE
[E::cram_read_container] Container header CRC32 failure

### ISSUE THREAD

**Issue by silvewheat** [brentp/mosdepth#30]
hello,
            when I use mosdepth in linux, an error occurred like this:
![image](https://user-images.githubusercontent.com/19344997/35366220-4e60c3d0-01b3-11e8-9a49-075cd31a9800.png)
           And, I run it in linux system, cram file.
           What could be causing it?
Thanks!

**Comment by brentp** [comment]
what mosdepth command did you run? on the cram that you used does samtools view give this same error?

**Comment by silvewheat** [comment]
mosdepth -t 2 -n -f ASM.fa test in.cram
and the samtools view command can work well.

**Comment by brentp** [comment]
can you share the cram and fasta privately? if so, send me an email and I'll have a look.

**Comment by silvewheat** [comment]
Thanks for your help!
And I try to remove -t option just now, the program than work well, it seems that the error only occur when parallel running.

**Comment by brentp** [comment]
hmm, well, that's not good, you might want to make sure you have the latest release of htslib. I have been able to use mosdepth on cram with > 1 thread.

**Comment by silvewheat** [comment]
I think cause of the issue found!
The reference index is older than the fasta file!
Thinks for your help, and very sorry for my mistake!
Thank you very much!
