### ISSUE TITLE
Empty "mosdepth.dist.txt" file

### ISSUE THREAD

**Issue by gwaygenomics** [brentp/mosdepth#31]
I am using the [mosdepth bioconda](https://bioconda.github.io/recipes/mosdepth/README.html) implementation to analyze coverage of a WES `bam` file. My command was:

```bash
mosdepth --by exons.bed example_prefix example_tumor.bam
```

The `example_prefix.mosdepth.dist.txt` file is empty after this command. Am I doing something wrong?

Other output files are populated. I do get several warnings about chromosome regions not found. (e.g. `[mosdepth] warning chromosome:chr1 from bed with 68500 regions not found`

Thanks!

**Comment by brentp** [comment]
can you show the output of `samtools view -H example_tumor.bam`? I that shows that the chroms are '1', '2', ... then you'd have to change exons.bed so that it does not include the 'chr' prefix.

**Comment by gwaygenomics** [comment]
That did it! Thanks for the quick response
