### ISSUE TITLE
Output only to two decimal places in $prefix.mosdepth.dist.txt

### ISSUE THREAD

**Issue by alizrrao** [brentp/mosdepth#32]
The current version of mosdepth (downloaded as a binary release) outputs cumulative distribution information only to two decimal places and has a lot of rows with 0.00 as a result. I noticed that an older version (downloaded Jan 4, 2018) output to 4 decimal places. E.g.:

#old version - $prefix.mosdepth.dist.txt:
```
chr1  591  0.0001  
chr1  590  0.0001  
chr1  589  0.0001  
...
total	2	0.9944
total	1	0.9978
total	0	1.0000
```

#current version - $prefix.mosdepth.dist.txt:
```
chr1  591  0.00  
chr1  590  0.00  
chr1  589  0.00
...
total	2	0.99
total	1	1.00
total	0	1.00
```

Please bring back the 4 decimal places in future releases. Thanks for this awesome tool!

**Comment by alizrrao** [comment]
Never mind, I see that this issue has been addressed. In case others run into the same issue, one can run the command as the following:

`env MOSDEPTH_PRECISION=4 mosdepth [command_options]`

**Comment by brentp** [comment]
glad you figured it out. I agree that it's not totally obvious from the README unless you know what you're looking for. I welcome any suggestions or PR improving the documentation.
