### ISSUE TITLE
Warnings about invalid chromosome intervals for very short contigs?

### ISSUE THREAD

**Issue by philippbayer** [brentp/mosdepth#33]
Turns out, I shouldn't write issues when I'm tired, I had mixed up the input files of course. The possible integer overflow error is still present

~~I'm running the latest mosdepth v0.2.1 using -b and a bed file from gff2bed and I'm getting numerous warnings like~~

~~[mosdepth] warning requested interval outside of chromosome range:4669..4765~~

~~But looking at the bed and fasta files I can't see where the invalid range is.~~

~~$grep -P '\t4669\t4765\t' *bed
jcf7180001448645_firstRound	4669	4765	evm.model.jcf7180001448645_firstRound.2.exon3	.	+	.	exon	.	ID=evm.model.jcf7180001448645_firstRound.2.exon3;Parent=evm.model.jcf7180001448645_firstRound.2~~

~~$grep jcf7180001448645_firstRound *fai
jcf7180001448645_firstRound	5521	501247228	60	61~~

~~So this contig is 5521 bases long, definitely enough for the gene.~~

~~The bam header says the same:~~

~~@SQ	SN:jcf7180001448645_firstRound	LN:5521~~

~~I do not see this warning for pseudomolecules, only for small-ish contigs <= 11kb.~~

~~Should this line really compare the *coverage* and the start? (not 100% sure what the coverage variable stores, don't know nim) https://github.com/brentp/mosdepth/blob/master/mosdepth.nim#L361~~

Unrelated, I'm also seeing what looks like integer overflows for highly repetitive pieces where the coverage is suddenly negative:

```
Scaffold02946   16      248     evm.model.Scaffold02946.1.exon1 174395057.34
Scaffold02946   323     526     evm.model.Scaffold02946.1.exon2 79154426.28
Scaffold02946   602     805     evm.model.Scaffold02946.1.exon3 -42867359.94
Scaffold02946   891     1357    evm.model.Scaffold02946.1.exon4 26488868.74
```

But for now I'm only interested in exons that have a coverage of 0.00 so I'm just ignoring those.

Thank you for your software, it is SO much faster and easy on the resources than what I've normally been using!

**Comment by brentp** [comment]
Any chance you can share a part of the bam that has the integer overflow?

**Comment by brentp** [comment]
I have made a change locally that might resolve the integer overflow, but if you could provide a small section of bam that replicates, I could test.

**Comment by philippbayer** [comment]
Funny enough, after deleting all of my borked runs and rerunning with the fixed mosdepth the coverage becomes positive:

```
Scaffold02946	16	248	evm.model.Scaffold02946.1.exon1	19.34
Scaffold02946	323	526	evm.model.Scaffold02946.1.exon2	22.50
Scaffold02946	602	805	evm.model.Scaffold02946.1.exon3	24.36
Scaffold02946	891	1357	evm.model.Scaffold02946.1.exon4	22.78
Scaffold02946	16	248	evm.model.Scaffold02946.1.exon1	21.65
```

Embarrassing for me! Not sure how it then got the integer overflow - does it keep some numbers around when scaffold names are missing from the bam or bed files?

That also closes the issue of course

**Comment by Heather1999** [comment]
Hello,
I got warning requested interval outside of chromosome range:248387608-248388535 and the output was 0 KB.
I further samtools viewed the bam version of chr1:248387608-248388535 and got something like this:

`LH00242:20:22F2FYLT3:2:1123:20593:12488 99      chr1    248388154       60      122M    =       248388154       122     CACCATGCTGAGGCTGGCCTGTGGGGACAAAACCACCTATGAAACAGTGATGTATGTGTGCTGCGTTGCAATGCTGCTGATCCCCTTCTCGGTGGTGACTGCATCCTACACCAGGATTCTCA      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      MC:Z:122M       AS:i:117        XS:i:20 LO:Z:L_L        RG:Z:AS_02N
LH00242:20:22F2FYLT3:2:1123:20593:12488 147     chr1    248388154       60      122M    =       248388154       -122    CACCATGCTGAGGCTGGCCTGTGGGGACAAAACCACCTATGAAACAGTGATGTATGTGTGCTGCGTTGCAATGCTGCTGATCCCCTTCTCGGTGGTGACTGCATCCTACACCAGGATTCTCA      FFFFFFFFFFF5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      MC:Z:122M       AS:i:117        XS:i:20 LO:Z:L_L        RG:Z:AS_02N
LH00242:20:22F2FYLT3:2:2259:39556:28654 83      chr1    248388155       60      151M    =       248388088       -218    ACCATGCTGAGGCTGGCCTGTGGGGACAAAACCACCTATGAAACAGTGATGTATGTGTGCTGCGTTGCAATGCTGCTGATCCCCTTCTCGGTGGTGACTGCATCTTACACCAGGATTCTCATCACAGTGCATCAGATGACATCGGCTGAAG FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF MC:Z:151M       AS:i:151        XS:i:0 LO:Z:L_L RG:Z:AS_02N
LH00242:20:22F2FYLT3:2:2157:18808:1417  81      chr1    248388156       60      151M    =       248387995       -312    CCATGCTGAGGCTGGCCTGTGGGGACAAAACCACCTATGAAACAGTGATGTATGTGTGCTGCGTTGCAATGCTGCTGATCCCCTTCTCGGTGGTGACTGCATCCTACACCAGGATTCTCATCACAGTGCATCAGATGACATCGGCTGAAGG FFFFFFFFFFFFFFFFFFF`

Is there anything wrong with my bam file? 
Thank you!
