### ISSUE TITLE
BAPQ filtering

### ISSUE THREAD

**Issue by EgirardBioinfo** [brentp/mosdepth#36]
Hi,
As filtering on base qualities is performed in most variant callers, it is important to take this metric into account when calculating the number of base pairs below a given threshold (especially in clinical analysis). Could you integrate this BAPQ filtering in your tool ? 
Thanks,

**Comment by brentp** [comment]
mosdepth can not do that. it is fast because it looks at chunks of reads (usually, this is just 1 big chunk). I will add this to an FAQ.
