### ISSUE TITLE
number of decimals in .global.list.txt

### ISSUE THREAD

**Issue by avilella** [brentp/mosdepth#38]
I discovered mosdepth to give me more info about coverage in my bams. I noticed the 'total' in `.global.dist.txt` reaches as deep as the highest depth in the file, but the value next to it only has 2 decimals. Am I running it correctly? How do I increase the number of decimals in the fraction? E.g. below

```
total   131     0.00
total   130     0.00
total   129     0.00
total   128     0.00
total   127     0.00
total   126     0.00
total   125     0.00
total   124     0.00
total   123     0.00
total   122     0.00
total   121     0.00
total   120     0.00
total   119     0.00
...
total   23      0.00
total   22      0.01
total   21      0.01
total   20      0.01
total   19      0.01
total   18      0.01
total   17      0.01
total   16      0.01
total   15      0.01
total   14      0.01
total   13      0.01
total   12      0.01
total   11      0.01
total   10      0.02
total   9       0.02
total   8       0.02
total   7       0.02
total   6       0.03
total   5       0.04
total   4       0.05
total   3       0.07
total   2       0.13
total   1       0.34
total   0       1.00
```

**Comment by avilella** [comment]
Misunderstood the output! Found it now: `MOSDEPTH_PRECISION=8`

**Comment by brentp** [comment]
Glad you figured it out. I think I might make the next release default to 3 or at least put out the first value at the highest possible precision as I agree that it's odd to see a bunch of zeros.

**Comment by avilella** [comment]
Thanks!
