### ISSUE TITLE
Build binaries with older glibc Centos 6

### ISSUE THREAD

**Issue by chapmanb** [brentp/mosdepth#4]
Brent;
Is it possible to provide the pre-build binaries on Centos 6 with an older glibc? When using the current binaries on older systems I get:
```
mosdepth: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by mosdepth)
```
It works fine on more up to date machines but we support these older ones with bioconda (and many bcbio HPC users have them).

**Comment by brentp** [comment]
Yes, I'll look into it.

**Comment by brentp** [comment]
I have started this by having a .travis.yml for this repo that builds from scratch. If someone can update the bioconda recipe to follow that (excluding htslib install and just using that as a dependency), then it should be exactly what you need. I'll have a look at it late this week or early next unless someone beats me to it.

**Comment by chapmanb** [comment]
Brent -- awesome, thank you. I've got a bioconda recipe that uses this to build and it seems to work great. I'll do a bit more testing and get it checked in tomorrow. Thanks for teaching me how to build things with nim.

**Comment by brentp** [comment]
wow. you're fast. thank you!
