### ISSUE TITLE
Weird results in `.region.dist.txt`

### ISSUE THREAD

**Issue by vladsaveliev** [brentp/mosdepth#40]
Brent,

I might be misunderstanding how `.region.dist.txt` is calculated. I generated a BED file from .fa.fai and passed it to mosdepth with `--by` option:

```
awk 'BEGIN {FS="\t"}; {print $1 FS "0" FS $2}' gdc-viral.fa.fai > gdc.bed
mosdepth diploid_tumor_viral_mapped_mosdepth diploid_tumor_viral.mapped.bam -n --thresholds 1,5 --by gdc.bed
```

I would expect to get identical results from `.global` and `.regions`, however:

```
grep -w 5 diploid_tumor_viral_mapped_mosdepth.mosdepth.region.dist.txt | sort -r -k3,3 | head
HPV45   5       1.00
HPV39   5       1.00
HPV35   5       1.00
HPV33   5       1.00
HPV31   5       1.00
HPV26   5       1.00
HPV18   5       1.00
total   5       0.01
HPV82   5       0.01
HPV71   5       0.01
```

```
grep -w 5 diploid_tumor_viral_mapped_mosdepth.mosdepth.global.dist.txt | sort -r -k3,3 | head
HPV18   5       1.00
total   5       0.01
HPV82   5       0.01
HPV71   5       0.01
HPV25   5       0.01
HPV21   5       0.01
HPV20   5       0.01
HPV19   5       0.01
HPV14   5       0.01
HCV-2   5       0.01
```

That's weird that HPV26 contig even appears in the stats, even though it is not present in the BAM file at all:

```
samtools view diploid_tumor_viral.mapped.bam | grep HPV26 | wc
0
```

I would blame the BED file if `.thresholds.bed.gz` didn't confirm the `.global` stats, not `.region`:

```
zcat diploid_tumor_viral_mapped_mosdepth.thresholds.bed.gz | grep -v ^# | awk 'BEGIN {FS="\t"} { print $1 FS $2 FS $3 FS $5 FS $5/($3-$2) }' | sort -r -k 5,5 | head
#chrom  start   end     region  5X
HPV18   0       7857    7857    1
HCV-1   0       9646    98      0.0101597
HCV-2   0       9711    97      0.00998867
HPV71   0       8037    78      0.00970511
HPV19   0       7685    72      0.0093689
HPV82   0       7870    60      0.00762389
HPV20   0       7757    58      0.00747712
HPV21   0       7779    54      0.00694177
HPV25   0       7713    47      0.00609361
HPV14   0       7713    42      0.00544535
```

Attaching a tarball with all the files (BAM, BED, mosdepth output). I'm using mosdepth 0.2.2.
[mosdepth_duploid_tumor_viral.tar.gz](https://github.com/brentp/mosdepth/files/1950665/mosdepth_duploid_tumor_viral.tar.gz)

**Comment by brentp** [comment]
I have a fix for this. would you test with the attached binary? It was triggered when there are tids in the regions file that have no reads in the bam.
and do you mind if I add your data to the repo as a test-case?
[mosdepth.gz](https://github.com/brentp/mosdepth/files/1951919/mosdepth.gz)

**Comment by vladsaveliev** [comment]
Brent, doesn't seem to be fixed:

```
wget https://github.com/brentp/mosdepth/files/1951919/mosdepth.gz
gunzip mosdepth.gz
chmod +x mosdepth
export LD_LIBRARY_PATH=/g/data3/gx8/extras/vlad/bcbio/anaconda/lib:LD_LIBRARY_PATH

./mosdepth diploid_tumor_viral.mapped_mosdepth_fix diploid_tumor_viral.mapped.bam -n --thresholds 5 --by <(awk 'BEGIN {FS="\t"}; {print $1 FS "0" FS $2}' /g/data/gx8/local/development/bcbio/genomes/Hsapiens/GRCh37/viral/gdc-viral.fa.fai)

grep -w 5 diploid_tumor_viral.mapped_mosdepth_fix.mosdepth.region.dist.txt | sort -r -k3,3 | head
HPV45   5       1.00
HPV39   5       1.00
HPV35   5       1.00
HPV33   5       1.00
HPV31   5       1.00
HPV26   5       1.00
HPV18   5       1.00
total   5       0.01
HPV82   5       0.01
HPV71   5       0.01
```

> and do you mind if I add your data to the repo as a test-case?

Sure, please add

**Comment by vladsaveliev** [comment]
Ah, perhaps that executable doesn't include the changes:

```
./mosdepth --version
mosdepth 0.2.2
```

**Comment by brentp** [comment]
shoot. you're right. I uploaded the wrong binary. can you try this one?
[mosdepth.gz](https://github.com/brentp/mosdepth/files/1953626/mosdepth.gz)

**Comment by brentp** [comment]
new release that fixes this is out:
https://github.com/brentp/mosdepth/releases/tag/v0.2.3
thanks again for test-case and report.
