### ISSUE TITLE
Fails for long chromosomes

### ISSUE THREAD

**Issue by kaspernie** [brentp/mosdepth#41]
`mosdepth `v. 0.2.2 from `bioconda `fails when run on a simple csi-indexed bam file with a chromosome longer than 537 Mb:

    curl https://raw.githubusercontent.com/samtools/samtools/develop/examples/toy.sam 2>/dev/null | sed -E 's/LN:(.*)/LN:6000000\1/' | awk -vOFS="\t" 'NR==1 {print} NR==3 {$4=$4+600000000;$5=$5+600000000;print}' | samtools view -b -otest.bam
    samtools index -c test.bam
    mosdepth test test.bam
Error message:
> [E::hts_idx_push] Region -1..600000006 cannot be stored in a csi index with min_shift = 14, n_lvls = 5. Try using min_shift = 14, n_lvls >= 6
> [hts-nim] error adding to csi index

It is likely somehow related to the max chromosomal length of 2^29 - 1 of `.tbi`/`.bai` indexes though it should not be a problem for a `.csi` index (max 2^31 - 1) which is mentioned in the error message.

Maybe a check is performed with the `.tbi`/`.bai` limit rather than the `.csi` limit. 

Maybe using an updated version of `htslib` would solve the issue.

See eg. https://github.com/samtools/samtools/issues/241 and https://github.com/samtools/htslib/pull/470

**Comment by brentp** [comment]
I just pushed a fix for this. Thanks for reporting and especially for the reproducible example.

**Comment by brentp** [comment]
new release with fix is here: https://github.com/brentp/mosdepth/releases/tag/v0.2.3
thanks again

**Comment by kaspernie** [comment]
Great! Thanks a lot!
