### ISSUE TITLE
Update BioConda Version with latest release 

### ISSUE THREAD

**Issue by IsmailM** [brentp/mosdepth#43]
Hey, 

Great Tool. 

Can you update the bioconda version with the latest version; as 0.2.2 has bugs in it, which have been fixed on github...

**Comment by wdecoster** [comment]
Bioconda is currently migrating to a new conda build (read more about this here: https://github.com/bioconda/bioconda-recipes/issues/9404). I guess updates will be for after the migration.

**Comment by wdecoster** [comment]
For reference, someone is already working on this: https://github.com/bioconda/bioconda-recipes/pull/9719

**Comment by cbrueffer** [comment]
Thanks @wdecoster , I was going to update this PR after merging :-)

**Comment by cbrueffer** [comment]
The updated package is available now, so this PR can be closed.
