### ISSUE TITLE
could not load: libhts.so

### ISSUE THREAD

**Issue by indapa** [brentp/mosdepth#49]
Hi Brent,

I installed mosdepth using bioconda but then I get the error:

```
mosdepth -h
could not load: libhts.so
compile with -d:nimDebugDlOpen for more information
```

When I installed, conda also installed htslib. I went looking for the libhts.so file:

```

ls /home/indapa/anaconda2/lib/ | grep hts
libhts.a
libhts.so
libhts.so.1.7
libhts.so.2

```
And then tried the following but the same error:

```

LD_LIBRARY_PATH=/home/indapa/anaconda2/lib mosdepth -h
could not load: libhts.so
compile with -d:nimDebugDlOpen for more information

```

I'm not sure what the best way forward is. I really want to use your tool so if you can help
point in the right direction, that would be great.

**Comment by brentp** [comment]
hmm. not sure. can you try `export LD_LIBRARY_PATH=/home/indapa/anaconda2/lib/; mosdepth -h` ?

**Comment by indapa** [comment]
```
 export LD_LIBRARY_PATH=/home/indapa/anaconda2/lib/; mosdepth -h
could not load: libhts.so
compile with -d:nimDebugDlOpen for more information

```

Same error. Should I just compile from source rather doing conda install?

**Comment by brentp** [comment]
conda install is failing? that should just work. what is the output of

```
env | grep -iP "python|conda|LD"
```

**Comment by indapa** [comment]
Sorry for the confusion. No, conda install mosdepth works just fine. 

conda and LD path  are in my environment

```

/home/indapa/anaconda2/bin
LD_LIBRARY_PATH=/home/indapa/anaconda2/lib/
```

**Comment by brentp** [comment]
can you try the binary distributed from the releases: https://github.com/brentp/mosdepth/releases/tag/v0.2.3 ?

**Comment by indapa** [comment]
oh man, nothing is working for me today. I downloaded the binary release:

```

export LD_LIBRARY_PATH=/home/indapa/anaconda2/lib/; ./mosdepth -h
could not load: libhts.so
compile with -d:nimDebugDlOpen for more information

```

**Comment by brentp** [comment]
I would just build htslib from source, export LD_LIBRARY_PATH to point to the source dir (containing the .so) and check that before anything else.

**Comment by brentp** [comment]
I have just experienced this where the LD_LIBRARY_PATH is set correctly, but the `could not load: libhts.so` message occurs. This occured on a shared drive where I had build htslib on a different machine with a newer GLIBC and then I tried to run mosdepth on a machine with an older GLIBC. I could see the problem by running: `ldd $LD_LIBRARY_PATH/libhts.so`

**Comment by kkapuria3** [comment]
I tried it with htslib1.9 compiled from source. Still gives,
`could not load: libhts.so'

I was wondering if there are any specific instructions to compile this from source in centos

**Comment by brentp** [comment]
what does `ldd $LD_LIBRARY_PATH/libhts.so` show?

**Comment by kkapuria3** [comment]
linux-vdso.so.1 =>  (0x00007fffe749f000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f2fa8d52000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f2fa8b41000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f2fa892b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2fa8629000)
        libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f2fa83aa000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f2fa7f4c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2fa7d30000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2fa7963000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2fa922b000)
        libnghttp2.so.14 => /usr/lib64/libnghttp2.so.14 (0x00007f2fa773e000)
        libidn2.so.0 => /usr/lib64/libidn2.so.0 (0x00007f2fa751d000)
        libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f2fa72f5000)
        libpsl.so.0 => /usr/lib64/libpsl.so.0 (0x00007f2fa7080000)
        libssl3.so => /usr/lib64/libssl3.so (0x00007f2fa6e35000)
        libsmime3.so => /usr/lib64/libsmime3.so (0x00007f2fa6c0e000)
        libnss3.so => /usr/lib64/libnss3.so (0x00007f2fa68eb000)
        libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f2fa66be000)
        libplds4.so => /lib64/libplds4.so (0x00007f2fa64ba000)
        libplc4.so => /lib64/libplc4.so (0x00007f2fa62b5000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f2fa6078000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2fa5e74000)
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f2fa5c27000)
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f2fa593f000)
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f2fa570c000)
        libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f2fa5509000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f2fa52fa000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f2fa50a8000)
        libunistring.so.0 => /usr/lib64/libunistring.so.0 (0x00007f2fa4d92000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f2fa4b21000)
        libicuuc.so.50 => /usr/lib64/libicuuc.so.50 (0x00007f2fa47ab000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f2fa45a3000)
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f2fa4395000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f2fa4192000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f2fa3f79000)
        libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007f2fa3d5e000)
        libicudata.so.50 => /usr/lib64/libicudata.so.50 (0x00007f2fa278b000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f2fa2406000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2fa21f0000)
        libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f2fa1fcf000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f2fa1d98000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f2fa1b96000)

**Comment by brentp** [comment]
ok. and you exported LD_LIBRARY_PATH before running mosdepth?

you can compile from source following: https://github.com/brentp/mosdepth/blob/master/scripts/build.sh

**Comment by kkapuria3** [comment]
Export was the problem. That was so silly.
