### ISSUE TITLE
per-base.bed.gz with --by

### ISSUE THREAD

**Issue by alhsu** [brentp/mosdepth#50]
I have a WGS BAM which I'd like to just get per-base coverage in regions in a BED file.

But when I use
mosdepth -Q 10 --threads 4 -b BED BASE BAM

The per-base.bed.gz generated is still for the whole genome. Can mosdepth output per-base coverage only for the given regions?

**Comment by pdiakumis** [comment]
I guess the answer is no based on this: https://github.com/brentp/mosdepth/issues/18

**Comment by brentp** [comment]
@pdiakumis is correct. it can not do that directly. however, you can simply intersect the per-base output with your `BED` to get what you want.
