### ISSUE TITLE
Base Quality Thresholding

### ISSUE THREAD

**Issue by jhl667** [brentp/mosdepth#53]
Hello!  This tool is pretty cool, definitely faster than the one I wrote for Python a while back.  Anyways, I'm wondering about computing a Q30% value per BED interval.  This would essentially be the number of bases in a particular region with at least phred base quality of 30 divided by the total number of bases in the region.  Similar to your threshold option, I could see this as a raw count of the number of times this happens, leaving the final division to the end user.  Thoughts on this?

**Comment by brentp** [comment]
`mosdepth` does not look at each base. that's part of what makes it fast. if you need to use the base-quality, you'll have to look at `samtools depth`.
