### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by johnomics** [brentp/mosdepth#54]
Hello @brentp, thank you for mosdepth, it's great.

I'm getting an out of memory error with 0.2.2 and a different error with 0.2.3:

v0.2.2:
```
mosdepth -b 1000 -n -t 50 -q 60 out in.bam
out of memory
```

v0.2.3:
```
mosdepth -b 1000 -n -t 50 -q 60 out in.bam
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

This is with a read set I have aligned to other genomes and a genome I have aligned other read sets to; mosdepth has worked fine on these other BAMs.

This is Oxford Nanopore data; basic stats for the read set:
```
 num_seqs         sum_len  min_len  avg_len  max_len     N50
2,051,690  12,566,075,726        5  6,124.7  265,781  13,969
```

And the genome:
```
num_seqs     sum_len  min_len   avg_len  max_len      N50
     408  19,282,250    1,000  47,260.4  956,893  300,798
```

Checking the BAM, there are reads mapping to 408 of the 408 contigs, so I don't think this looks like the bug that was fixed in 0.2.3.

Based on the region.dist.txt and global.dist.txt files, mosdepth processed 191 of the 408 contigs when it crashed. The last line is reporting for 0x coverage so it looks like it got through the 191st contig completely. That contig was 1706bp long; the next contig to be processed (according to the BAM header) was 28845bp long.

Any ideas as to what might be happening here?

Thanks
John

**Comment by brentp** [comment]
hmm. thanks for reporting. any chance you can share the bam or a part of it that is enough to reproduce this error?

does it fail if you use a single thread? by the way, there's no point in using more than about 4-5 threads as those are decompression threads an that should saturate pretty quickly.

**Comment by johnomics** [comment]
Thanks for looking into this. With a single thread, I get the out of memory error with 0.2.3, not Illegal storage access.

Test BAM with results:
https://www.dropbox.com/s/ohnxdijchhhs3d6/mosdepth_test.tar.gz?dl=0

```
$ mosdepth -b 1000 -n -q 60 mosdepth_test mosdepth_test.bam
out of memory
```

This BAM includes the last contig that passed successfully and the next one that appears to be failing.

**Comment by brentp** [comment]
great. thanks. I can see the problem and will make a new release next week. meanwhile, you can get past this error by using ` -q :60: ` instead of `-q 60`

**Comment by johnomics** [comment]
Thank you very much, `-q :60:` worked! Really appreciate the quick response. Best wishes

**Comment by brentp** [comment]
no problem. I'll leave this open til I make the new fix and release. thanks for the test-case.

**Comment by estolle** [comment]
hi there
I apparently encountered this problem as well (version DL 2d ago, v0.2.5 as binary). It seems it happends independent of the -t option, but when I use the -q option like this: --quantize 0:1:5:100 . It fails for 3 out of 50ish bam files with "out of memory" of "SIGSEGV: Illegal storage access. (Attempt to read from nil?)". I had the exact same command/bam file producing one time the first error message, one time the other error message.

As suggested in this post, I added a colon after the last -q number ("--quantize 0:1:5:100:") and now it seems to work. I see on the README that your example has it the same way but I thought it was a typo as its not clear why the needs to be a colon at the end. 

Even though I can run the bam files now, I wanted to report the issue in case its useful.

my command with the error messages:

mosdepth --threads 4 --by 20000000 --no-per-base --fast-mode --quantize 0:1:5:100 mosdepth/$SAMPLE $SAMPLE.bam
out of memory

same command
mosdepth --threads 4 --by 20000000 --no-per-base --fast-mode --quantize 0:1:5:100 mosdepth/$SAMPLE $SAMPLE.bam
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

mosdepth --by 20000000 --no-per-base --fast-mode --quantize 0:1:5:100 mosdepth/$SAMPLE $SAMPLE.bam
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

mosdepth --threads 4 --by 10000000 --no-per-base --fast-mode --quantize 0:1:5:100 mosdepth/$SAMPLE $SAMPLE.bam
out of memory

mosdepth --threads 4 --by 20000000 --no-per-base --fast-mode mosdepth/$SAMPLE $SAMPLE.bam
worked

changed the -q (additional colon at the end):
mosdepth --threads 4 --by 20000000 --no-per-base --fast-mode --quantize 0:1:5:100: mosdepth/$SAMPLE $SAMPLE.bam
works ok

**Comment by brentp** [comment]
any chance could you share one of the bams that had a problem?

**Comment by estolle** [comment]
sent you an email with a link to the .bam
thanks for looking into this!

**Comment by brentp** [comment]
thanks so much. I got the bam, found the problem, and have a fix. I'll make a new release this week.

**Comment by brentp** [comment]
will you give this binary a try? (assuming you're on 64bit linux)
[mosdepth_fix.gz](https://github.com/brentp/mosdepth/files/2979074/mosdepth_fix.gz)

**Comment by estolle** [comment]
the new binary works! thanks for fixing it!

**Comment by brentp** [comment]
great! thanks for following up.
