### ISSUE TITLE
per-base coverage, break out into per-base for each position

### ISSUE THREAD

**Issue by stephenturner** [brentp/mosdepth#55]
Not a bug, and probably a @arq5x bedtools operation, but asking here because this started with mosdepth. The per-base coverage output collapses consecutive bases with identical coverage into a single interval:

```
MT      95      96      4184
MT      96      98      4214
MT      98      99      4222
```

My coverage at position 96 on chromosome MT is 4184x, 97 and 98 is 4214X, and 99 is 4222x.

I'd like to break this out to get a single entry for every single base. E.g., something like

```
MT      95      96      4184
MT      96      97      4214
MT      97      98      4214
MT      98      99      4222
```

What's the best way to accomplish this?

**Comment by arq5x** [comment]
```bedtools makewindows -b foo.bed -w 1 -i src``` should do it.

**Comment by brentp** [comment]
Aaron's too fast (still got it), but you can also use `awk '{for(i=$2;i<$3;i++){ print $1,i,i+1,$4 } }'`

**Comment by stephenturner** [comment]
Thanks gentlemen. 6 minutes to two working solutions. You rock.
