### ISSUE TITLE
OSX build for bioconda

### ISSUE THREAD

**Issue by virenar** [brentp/mosdepth#57]
I am using macOS v10.13.6 and tried installing mosdepth in my env with the following command

`conda install -c bioconda mosdepth==0.2.3`

However, I got the following error
```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mosdepth==0.2.3

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by splichte** [comment]
I don't think this is an error. The package is not listed on bioconda as available for Mac OS X, only for Linux. 
See: http://bioconda.github.io/recipes.html

I see the same result as you on Mac OS X, but the package is available on Linux (Ubuntu in my case).

**Comment by brentp** [comment]
it'd be great to have a bioconda build for osx, i'm not sure how to do that.

**Comment by nuin** [comment]
I was able to build on macOS using `nimble`, the only issue is that I see 

```
mosdepth] WARNING: built in debug mode; will be slow
```

and it would be interesting to build in non-debug mode.

**Comment by nuin** [comment]
I have

`Nim Compiler Version 1.2.4 [MacOSX: amd64]`

and 

`nimble v0.11.4 compiled at 2020-06-28 06:12:35`

**Comment by brentp** [comment]
@nuin , thanks for trying it out. if you use `nimble install` it will create a release build. or you can do: `nim c -d:danger -d:release mosdepth.nim`

**Comment by nuin** [comment]
@brentp I did the `nimble install` and it still gave me a debug version. I will try the direct nim compilation

**Comment by nuin** [comment]
It works fine too with an incredible speedup

Using debug version
`mosdepth -t 16 --by /opt/BED/Inherited_Cancer_panel_FINAL.bed test   138.59s user 2.85s system 110% cpu 2:07.53 total`

Using release
`~/src/mosdepth/mosdepth -t 16 --by /opt/BED/Inherited_Cancer_panel_FINAL.bed   37.84s user 2.98s system 113% cpu 36.041 total`

same file, targeted sequencing BAM file. I am investigating the possibility of creating a condo package on macOS.

**Comment by nuin** [comment]
Just did a fresh install of Conda on my machine and set the Bioconda channel, got this


```
❯ conda install mosdepth
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libcxx conflicts for:
mosdepth -> pcre[version='>=8.44,<9.0a0'] -> libcxx[version='>=10.0.0']
python=3.7 -> libcxx[version='>=4.0.1']
python=3.7 -> libffi[version='>=3.3,<3.4.0a0'] -> libcxx[version='>=10.0.0']
```

**Comment by brentp** [comment]
hmm. i don't think mosdepth depends on pcre any more, so this sould be an easy fix within bioconda

**Comment by nuin** [comment]
PCRE is still listed on the Readme.md on the main page

`mosdepth also requires a recent version of PCRE, and will give the error could not import: pcre_free_study if the version of PCRE on your system is too old. If you do not have root and cannot get the system version of PCRE upgraded, you download and compile a local copy`

**Comment by brentp** [comment]
hmm. I will test thanks for pointing that out.
