### ISSUE TITLE
Feature request: filter by readgroup

### ISSUE THREAD

**Issue by chrisamiller** [brentp/mosdepth#60]
Many groups are now doing eWGS, where an exome and whole-genome are created from different libraries, but sequenced together (with different indices). They're generally aligned together into one bam/cram, since we want all the possible depth for making variant calls.

The problem is, that in order to do WGS copy number calling, we generally have to make a separate bam of just the WGS data. If mosdepth supported extracting only certain readgroups, that would save a lot of time. (or if it supported streamed input somehow, so that we could filter on the fly).

Undoubtedly, this would slow things down during that use case, because you'd have to decode those fields, but should still result in a substantial overall speed-up for eWGS workflows that now have to create a new bam

**Comment by brentp** [comment]
this would be useful. a test-case of chr22 with data like this would be a helpful start.

**Comment by chrisamiller** [comment]
Thanks! Here's an eWGS bam from chr22 of HCC1395, and the fasta to which it was aligned.
https://xfer.genome.wustl.edu/gxfer1/project/cancer-genomics/mosdepth/

```
WGS Read groups:
2895499225
2895499232
2895499236
2895499338

Exome Read groups:
2895499223
2895499234
2895499237
2895499240
2895499248
2895499337
2895499355
2895499400
```
Just let me know if there's other info that would be useful

**Comment by brentp** [comment]
thank you. I am swamped at the moment but will get this in soon.

**Comment by chrisamiller** [comment]
No worries - thanks for looking into it!

**Comment by brentp** [comment]
I implemented this. you can specify `--read-groups aaa,bbb,ccc` to limit to.
Here's a binary for testing. I'll likely make a release next week.
thanks very much for the test-data and the idea.

[mosdepth.gz](https://github.com/brentp/mosdepth/files/2516572/mosdepth.gz)

**Comment by chrisamiller** [comment]
Awesome - thanks!
