### ISSUE TITLE
cannot run mosdepth with only --fast-mode as option

### ISSUE THREAD

**Issue by kkapuria3** [brentp/mosdepth#62]
When I try to run mosdepth (conda installed and updated), I still cannot make it run with --fast-mode flag. When I try to do that it just prints help. Other flags work fine. Do you have any idea about this ?

**Comment by brentp** [comment]
the bioconda version is probably not the latest mosdepth, eh?

**Comment by kkapuria3** [comment]
Let me try it right away.
