### ISSUE TITLE
Median coverage per-window

### ISSUE THREAD

**Issue by shahmj** [brentp/mosdepth#64]
Hi,

Is there a way for mosdepth to output median coverage per-window instead of mean?

Thanks,
Minita

**Comment by brentp** [comment]
not currently, but this could be implemented pretty efficiently so I'll leave this open as a feature request.

**Comment by shahmj** [comment]
Ok, great. Thanks!

**Comment by hdashnow** [comment]
I'd also find this useful.

**Comment by brentp** [comment]
this is implemented in recent releases.
