### ISSUE TITLE
Bug in coverage calculation with specific quantization settings

### ISSUE THREAD

**Issue by gabeng** [brentp/mosdepth#66]
I noticed that I get false coverage results when using specific quantization parameters. 
When using
```
mosdepth -n -q 20:40: -t 4 prefix input.bam
zcat prefix.quantized.bed.gz  | grep GL000207.1
```
the result is
```
GL000207.1      115     146     20:40
GL000207.1      155     309     20:40
GL000207.1      323     324     20:40
...
GL000207.1      15686   16158   20:40
GL000207.1      16160   16292   20:40
GL000207.1      16293   16303   20:40
```
These values are way beyond the contig limits and are certainly not part of the BAM file. 

However, when I use these quantization settings:
```
mosdepth -n -q 0:20:40: -t 4 prefix input.bam
zcat prefix.quantized.bed.gz  | grep GL000207.1
```
the result is:
```
GL000207.1      0       4262    0:20
```
(which is correct).

The issue seems to be present when I apply thresholding by omitting the interval 0:threshold in the command line. 

So far, I have found this issue with a single `bam` file because it is so obvious on this contig.

**Comment by brentp** [comment]
can you verify that you are using the latest release? And is there any chance you can share part of the bam that recreates this?

**Comment by brentp** [comment]
thanks for providing the bam. I ran:
```
mosdepth -n -q 20:40: -t 4 prefix mosdepth-test.bam
zgrep GL000207.1 prefix.quantized.bed.gz
```
and get no output, so I think this is fixed in 0.2.4.

**Comment by gabeng** [comment]
Ok, great. Thanks for checking.

**Comment by brentp** [comment]
sure. let me know if you hit any more problems.
