### ISSUE TITLE
Running using docker

### ISSUE THREAD

**Issue by alok123t** [brentp/mosdepth#69]
For MacOS users, you can easily run using Docker!

Pull the required version from [quay](https://quay.io/repository/biocontainers/mosdepth?tab=tags)
(Use a particular tag, instead of ~~latest~~ which is the default and does not point to any tag)
And use docker run with volume containing path to directory containing data

```shell
docker pull quay.io/biocontainers/mosdepth:0.2.4--he527e40_0
docker run -v /Users/alok/Data/:/opt/mount --rm quay.io/biocontainers/mosdepth:0.2.4--he527e40_0 mosdepth -n --fast-mode -t 4 --by 1000 /opt/mount/sample /opt/mount/1.bam
```

Docker Parameters
-v /hostPath:/containerPath
Let host path be the path to a directory containing bam file (so you need not mount both bam and index file)
BAM file is directly accessible with the same name inside mount
--rm Cleanup once container exits

It would be great if you can add this to the README :)

**Comment by brentp** [comment]
I have added this to the readme. thank you.
