### ISSUE TITLE
Docker for mosdepth

### ISSUE THREAD

**Issue by thanhleviet** [brentp/mosdepth#7]
Thanks for a nice tool. Since I use Mac and the binary of mosdepth is for linux only, I ended up with a docker version.
Link for the Dockerfile: https://gist.github.com/thanhleviet/3797c773b060df75473b6c1263cdd8cf
The docker image is about 342 MB, it's not too big.

Then I can run the dockerized mosdepth as following:

`docker run --rm -it -v $PWD:/data thanhleviet/mosdepth my-file.bam > my-file-bam.cov`

**Comment by brentp** [comment]
nice! if you make sure it builds with libcurl and supports s3 urls, it'd be great if you opened a PR to put the Dockerfile in the repo root.

**Comment by brentp** [comment]
closing this for now as all bioconda packages get Dockerfiles. However, I will accept a PR that adds a dockerfile to the root of this repo.
