### ISSUE TITLE
Fully overlapping reads not detected (frequent in Amplicon data)

### ISSUE THREAD

**Issue by jaudoux** [brentp/mosdepth#72]
Hi @brentp,

I was checking the mosdepth _coverage_ procedure that looks at overlapping read pairs to avoid counting twice the coverage on the overlap section. I might be mistaken, but I think that the case were both reads are fully overlapping, as it frequently occurs with amplicon data, is not covered by the condition at this line (where it should be `rec.start <= rec.matepos`) : https://github.com/brentp/mosdepth/blob/a7622f289a2d19ef9270f1ab36c7410738580352/mosdepth.nim#L262

Best,
Jérôme.

**Comment by brentp** [comment]
hmm. I don't see anything wrong with your reasoning.
do those get mapped as proper pairs? when I see that, usually the mate is unmapped.

**Comment by jaudoux** [comment]
Yes they do get mapped as proper pairs, for example :

```
M00551:66:000000000-B6BF6:1:2103:9642:22936     99      1       565174  0       80M     =       565174  80      CCACAGAAGCTGCCATCAAGTATTTCCTCACGCAAGCAACCGCATCCATAATCCTTCTAATAGCTATCCTCTTCAACAAT        CCCCCGGFFGFEFGGGGFFFGGGGGDGGGGGFGGGGGFGGGEGCGFGGGFFGGGGGGGGGGCFGGFGGGFADEFGGG,FF        NM:i:0  MD:Z:80 AS:i:80 XS:i:80 XA:Z:M,+4624,80M,0;
     RG:Z:9d7d1b21-a694-416f-8d65-84d0fb943040
M00551:66:000000000-B6BF6:1:2103:9642:22936     147     1       565174  0       80M     =       565174  -80     CCACAGAAGCTGCCATCAAGTATTTCCTCACGCAAGCAACCGCATCCATAATCCTTCTAATAGCTATCCTCTCCAACAAT        CFCF<E<<@B@GEGFCGFAFGFECEC:GGGGFCE,F:C6GECCFFCFGF<68FC-GDGFEGGFC;C8@EFC--FFC8--C        NM:i:1  MD:Z:72T7       AS:i:75 XS:i:75 XA:Z:M,-4624,80M,1;     RG:Z:9d7d1b21-a694-416f-8d65-84d0fb943040
```

If needed, I can share a BAM file with aligned reads of amplicon data downloaded from [illumina's sequencing data examples](https://www.illumina.com/informatics/sequencing-data-analysis/data-examples.html).

**Comment by brentp** [comment]
can you make a sam with just those 2 alignments so I can use it in the test suite? or a PR with the fix and the test would be great.

**Comment by jaudoux** [comment]
PR sent : https://github.com/brentp/mosdepth/pull/73
