### ISSUE TITLE
plot-dist.py output file blank

### ISSUE THREAD

**Issue by albinap** [brentp/mosdepth#75]
Hi I am running mosdepth on some low coverage (3-7x) WGS sheep genomes. 
Mosdepth command

mosdepth -n --fast-mode -t 4 --by 50000 sample1 sample.NU.realigned.bam

The command seems to work and I have run it for several samples. Then I want to plot the output 

python $scripts/mosdepth/plot-dist.py *.global.dist.txt

This also work but the file I get is blank, that is it has some lines and numbers but no actual data

**Comment by brentp** [comment]
can you share 1 or 2 of the global.dist.txt files so I can have a look?
and/or, can you run it on subsets of the global.dist.txt files to see if it's 1 or 2 bad files that's causing a problem?

**Comment by albinap** [comment]
[VSH021.O.aries.NU.mosdepth.global.dist.txt](https://github.com/brentp/mosdepth/files/2971640/VSH021.O.aries.NU.mosdepth.global.dist.txt)

**Comment by albinap** [comment]
I have run mosdepth a few times with different window sizes and on different samples but the plot is always blank.

**Comment by brentp** [comment]
you can change line 20 of plot-dist.py to:
`            if chrom.startswith(("GL", "AMG", "JH")):`
you have so many small chromosomes that it's causing problems. With that change it will just plot the numbered chroms and X

**Comment by albinap** [comment]
Great, that fixed it, now there are many colored lines but the legend is so big that it is going over the graph
![image](https://user-images.githubusercontent.com/25434560/54442014-c4acab80-4735-11e9-8687-392a35224ba3.png)

**Comment by brentp** [comment]
just edit it to turn off the legend. on line 90 just change true to false.

**Comment by gubrins** [comment]
Heys @brentp ! I'm having the same issue but I'm working with a non-model organism, so chromosome's names are different. I tried to attach my global.dist file but is bigger than 10MB...
