### ISSUE TITLE
I am not able to install your software 

### ISSUE THREAD

**Issue by beginner984** [brentp/mosdepth#76]
Hi,

Whatever I am trying I am getting error in installing your software, any help please

> install_github("chrisamiller/copycat")
Downloading GitHub repo chrisamiller/copycat@master
These packages have more recent versions available.
Which would you like to update?

1:   glue    (1.3.0 -> 1.3.1) [CRAN]
2:   stringi (1.3.1 -> 1.4.3) [CRAN]
3:   CRAN packages only
4:   All
5:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 4
glue    (1.3.0 -> 1.3.1) [CRAN]
stringi (1.3.1 -> 1.4.3) [CRAN]
Skipping 3 packages not available: DNAcopy, doMC, IRanges
Installing 3 packages: doMC, glue, stringi
Installing packages into ‘C:/Users/fi1d18/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘doMC’ is not available (for R version 3.5.1)
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> install.packages("doMC")
Installing package into ‘C:/Users/fi1d18/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘doMC’ is not available (for R version 3.5.1)
> install_github("chrisamiller/copycat")
Downloading GitHub repo chrisamiller/copycat@master
These packages have more recent versions available.
Which would you like to update?

1:   glue    (1.3.0 -> 1.3.1) [CRAN]
2:   stringi (1.3.1 -> 1.4.3) [CRAN]
3:   CRAN packages only
4:   All
5:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 5
√  checking for file 'C:\Users\fi1d18\AppData\Local\Temp\RtmpgBzCfI\remotes21e412fc61f7\chrisamiller-copyCat-1bbbf5b/DESCRIPTION' ...
-  preparing 'copyCat':
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'copyCat_1.6.12.tar.gz'
   
Installing package into ‘C:/Users/fi1d18/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
ERROR: dependency 'doMC' is not available for package 'copyCat'
* removing 'C:/Users/fi1d18/Documents/R/win-library/3.5/copyCat'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/fi1d18/AppData/Local/Temp/RtmpgBzCfI/file21e454243881/copyCat_1.6.12.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> install_github("chrisamiller/copycat")
Downloading GitHub repo chrisamiller/copycat@master
These packages have more recent versions available.
Which would you like to update?

1:   glue    (1.3.0 -> 1.3.1) [CRAN]
2:   stringi (1.3.1 -> 1.4.3) [CRAN]
3:   CRAN packages only
4:   All
5:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
glue (1.3.0 -> 1.3.1) [CRAN]
Installing 1 packages: glue
Installing package into ‘C:/Users/fi1d18/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/glue_1.3.1.zip'
Content type 'application/zip' length 172471 bytes (168 KB)
downloaded 168 KB

package ‘glue’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘glue’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

Restarting R session...

> install_github("chrisamiller/copycat")
Error in install_github("chrisamiller/copycat") : 
  could not find function "install_github"
> install_github("chrisamiller/copycat")
Error in install_github("chrisamiller/copycat") : 
  could not find function "install_github"
> library(devtools)
Error: package or namespace load failed for ‘devtools’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘glue’
> install.packages("glu")
Installing package into ‘C:/Users/fi1d18/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘glu’ is not available (for R version 3.5.1)
> install.packages("glue")
Installing package into ‘C:/Users/fi1d18/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/glue_1.3.1.zip'
Content type 'application/zip' length 172471 bytes (168 KB)
downloaded 168 KB

package ‘glue’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\fi1d18\AppData\Local\Temp\Rtmp8iOkf0\downloaded_packages
> install_github("chrisamiller/copycat")
Error in install_github("chrisamiller/copycat") : 
  could not find function "install_github"
> library(devtools)
> install_github("chrisamiller/copycat")
Downloading GitHub repo chrisamiller/copycat@master
These packages have more recent versions available.
Which would you like to update?

1:   stringi (1.3.1 -> 1.4.3) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 2
√  checking for file 'C:\Users\fi1d18\AppData\Local\Temp\Rtmp8iOkf0\remotes3e0c73de75a6\chrisamiller-copyCat-1bbbf5b/DESCRIPTION' (376ms)
-  preparing 'copyCat':
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'copyCat_1.6.12.tar.gz'
   
Installing package into ‘C:/Users/fi1d18/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
ERROR: dependency 'doMC' is not available for package 'copyCat'
* removing 'C:/Users/fi1d18/Documents/R/win-library/3.5/copyCat'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/fi1d18/AppData/Local/Temp/Rtmp8iOkf0/file3e0c7d0c5d60/copyCat_1.6.12.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
>

**Comment by brentp** [comment]
seems you opened this issue on the wrong repo? there is nothing related to mosdepth in there.
