### ISSUE TITLE
tmp dir

### ISSUE THREAD

**Issue by nservant** [brentp/mosdepth#79]
Hi, 
I have an error that occurs randomly with mosdepth
```
[mosdepth] could not open file:/tmp//A1127C96_markdup_mosdepth_output.mosdepth.global.dist.txt
../root/.nimble/pkgs/hts-0.2.7/hts/bgzf.nim(52) open
```
I guess that, at some point, it tries to write a tmp file, and to reload it later.
Not sure it comes from mosdepth itself ...
However it would great to be able to modify the tmp folder ...
Do you think you can add such option !?
Many thanks
Nicolas

**Comment by brentp** [comment]
`export TMPDIR=/wherever`
and mosdepth will respect that. This is an odd error though. Can you show the full command and full stdout/stderr?

**Comment by nservant** [comment]
Sorry. My fault. I was storing the results in /tmp/
N
