### ISSUE TITLE
"Out of memory" if the BED file has track lines

### ISSUE THREAD

**Issue by lbeltrame** [brentp/mosdepth#8]
When trying mosdepth on a machine with 128G RAM (of which 123 free) I get an "out of memory" error with no additional explanation. The reason lies in the BED file being used, which has one track for display in the UCSC genome browser:

```
track name='Gene panel' description='Regions of interest'
```

Removing the line allows the calculation to proceed.

**Comment by brentp** [comment]
thanks for reporting. I pushed a fixed for this and tagged version 0.1.7.
