### ISSUE TITLE
Exit status zero upon error

### ISSUE THREAD

**Issue by wdecoster** [brentp/mosdepth#80]
Hi Brent,

I noticed that mosdepth returns an error status code of 0 with an incorrect command line. I'm not sure if that's a bug, but for me it was at least unexpected.

To reproduce:
```
$ mosdepth -t4prefix sample.bam
Usage: mosdepth [options] <prefix> <BAM-or-CRAM>
$ echo $?
0
```

This just needed a space between "4" and "prefix". After fixing this the error status code becomes non-zero as expected:
```
$ mosdepth -t4 sample sample.bam
[E::hts_open_format] Failed to open file sample.bam
[hts-nim] could not open 'sample.bam'. No such file or directory
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
$ echo $?
1
```

I noticed this when chaining command with `&&`, but it would also trip up a snakemake workflow, for example.

Cheers,
Wouter

**Comment by brentp** [comment]
this is fixed. will be out in next release. thanks for reporting.
