### ISSUE TITLE
Question regarding Fast-Mode

### ISSUE THREAD

**Issue by duartemolha** [brentp/mosdepth#82]
I have tried mosdepth with and without fast mode (-x) and was surprised to see the large differences I am getting with the 2. 

In my (small test), it seems -x is giving results more comparable with samtools depth (which surprised me

Can you explain better what exactly is different between the fast mode and the non-fast mode and why are counts on "slow" mode less comparable with samtools? I expected the opposite

**Comment by brentp** [comment]
the main reason you'd see large differences is if you have a lot of overlapping reads. you can verify this by looking at your insert size distribution.
the reason fast-mode is more similar to samtools depth is that samtools depth defaults to min base-quality and mapping-quality 0 but it sets overlapping bases to have base-quality 0 (so they still get counted). you can adjust this by running samtools depth with -q 1 (and -Q 1).
