### ISSUE TITLE
reference fasta file

### ISSUE THREAD

**Issue by kruthikaiyer0990** [brentp/mosdepth#85]
Hi!

From your documentation, I gather that for querying cram files, a reference fasta file is required. But I'm not entirely certain what the case is with bam files.
Would there be issues when querying bams in the absence of a reference fasta file?
And if it is optional, I wanted to know how it would impact the results - as in how different would the output be with and without a reference fasta file when the input is a bam file.

Thanks.

**Comment by brentp** [comment]
the fasta is only required for CRAM. for BAM, the result will be unchanged whether you specify it or not.
