### ISSUE TITLE
Is running on remote BAMs or STDIN possible?

### ISSUE THREAD

**Issue by edawson** [brentp/mosdepth#86]
Hi,

   I've got a use case where I have some massive BAM files on a remote server (well, specifically in this case, SRA).

 I'd like to calculate quantized depth over regions, but I don't have nearly enough local disk to pull in more than a piece of each BAM at a time. Mosdepth is my go-to tool for this when I do have BAMs.

Is there any chance the curl functionality from htslib still works here? Alternatively, is it possible to read from STDIN so I can pull regional reads using the sra tools and then calculate depth on those?

**Comment by brentp** [comment]
yes, you'll just need to use the non-static mosdepth (mosdepth_shared) release and have a libhts.so that is linked with libcurl. It is not possible to read from stdin though.

**Comment by edawson** [comment]
Awesome! I'll go ahead and close this. Thanks!
