### ISSUE TITLE
plot-dist.py  scripts not working

### ISSUE THREAD

**Issue by snashraf** [brentp/mosdepth#9]
Hi Brent,

Sorry for another silly question !! 
I have run mosdepth on an exome Sample.
mosdepth --by testTarget.bed 0200136071.bwa.bam  > test.dist
my bed file is 3 column bed files and now I am using this file test.dist for plotting using plot-dist.py  so I am getting below error.
Traceback (most recent call last):
  File "plot-dist.py", line 23, in <module>
    for x, y in (x.rstrip().split("\t") for x in open(f)):
ValueError: too many values to unpack
 I know why this error is coming but I am just wondering if I am missing something to that I can plot using that script. 

Can you please help me on this !!

Thanks

**Comment by brentp** [comment]
plot-dist is for dist files so your command would be:
```
mosdepth -d x.dist --by testTarget.bed 0200136071.bwa.bam > test.dist
python plot-dist.py x.dist
```
