### ISSUE TITLE
Evaluated coverage only over non-N bases in the given genome reference

### ISSUE THREAD

**Issue by xuyangy** [brentp/mosdepth#90]
Is it possible to evaluate coverage only over non-N bases in the given reference genome like Picard's CollectWgsMetrics does? There are over 200 million N-bases in GRch37 reference genome. All these N-bases will be counted as 0-coverage by mosdepth.

**Comment by brentp** [comment]
you can do this by giving bed file of the non-n regions. or by adusting the resulting values post-hoc.

**Comment by xuyangy** [comment]
Thanks. Some post calculation can be easily done. I have an established coverage threshold for coverage given by Picard's CollectWgsMetricsPicard, say over 30X larger than 90%. After switching to mosdepth, I need a comparable coverage threshold. CollectWgsMetrics does some default filtering by Base Quality and Mapping Quality in addition to excluding N-bases in reference. This make comparison between the output of Picard's CollectWgsMetrics and mosdepth's output a bit hard. 

But that's not mosdepth's issue. I will close this one.
