### ISSUE TITLE
Add mosdepth v0.2.6 to bioconda

### ISSUE THREAD

**Issue by iranmdl** [brentp/mosdepth#93]
Hello!
Could it be possible to add the latest mosdepth release (v0.2.6) to bioconda?
Thank you in advance,

**Comment by wdecoster** [comment]
It seems that was already attempted, listing PRs for reference:

- https://github.com/bioconda/bioconda-recipes/pull/15495
- https://github.com/bioconda/bioconda-recipes/pull/15826
- https://github.com/bioconda/bioconda-recipes/pull/15470

**Comment by iranmdl** [comment]
Thanks for the quick reply, I will keep an eye on the PRs to see when v0.2.6 gets available on bioconda :)

**Comment by iranmdl** [comment]
Fixed it! Thanks!
