### ISSUE TITLE
MosDepth -F 1804 versus -F 1796

### ISSUE THREAD

**Issue by lemdcock** [brentp/mosdepth#94]
Dear Brent, 

I ran into an issue running MosDepth on one of my BAM-files. With the default settings I get a mean coverage of around 45, while when I change the flag to 1804 (BCBio settings) the coverage drops to 23.4. Which is very weird as I have, based on samtools flagstat, only very few unmapped mates.

Do you have any idea where it's going wrong? 

Samtools flagstat output:
137208268 + 0 in total (QC-passed reads + QC-failed reads)
621688 + 0 secondary
366134 + 0 supplementary
0 + 0 duplicates
135966992 + 0 mapped (99.10% : N/A)
136220446 + 0 paired in sequencing
68110223 + 0 read1
68110223 + 0 read2
133712436 + 0 properly paired (98.16% : N/A)
134626302 + 0 with itself and mate mapped
352868 + 0 singletons (0.26% : N/A)
520020 + 0 with mate mapped to a different chr
290563 + 0 with mate mapped to a different chr (mapQ>=5)

MosDepth Command (Default):
mosdepth \
-n \
--by my_target.bed \
-t 3 \
--fast-mode \
my_out \
my_bam.bam

MosDepth Command (BCBio):
mosdepth -t 3 -F 1804 --no-per-base \
--by my_target.bed  \
my_out \
my_bam.bam

Kind regards,
Laurenz De Cock

**Comment by brentp** [comment]
in one case you are using --fast-mode which does not look at the cigar. in the other you are looking at the cigar which will skip over deletions and such.

**Comment by lemdcock** [comment]
My apologies, I have completely overlooked that. I will look into this. Thank you

**Comment by brentp** [comment]
no problem. glad that resolves it.
