### ISSUE TITLE
Not able to plot coverage graphs

### ISSUE THREAD

**Issue by Rohit-Satyam** [brentp/mosdepth#95]
Hi 

I am trying to make plots using mosdepth.global.dist.txt file. I downloaded the mosdepth in conda 4.7.12, Python 3.7.4. I have following queries

1. What is the command in conda to make plot's. It appears it's missing.
2. I made plot's finally making a copy of your plot-dist.py. However it is a number of plot's for each chromosome. Can they be combined in a single plot.

![Graph](https://user-images.githubusercontent.com/55479480/68528953-379b1000-031f-11ea-81a9-e271951b65b0.png)

**Comment by brentp** [comment]
there is a `total` plot that combines all of the chromosomes. You can also edit the script to your needs.

**Comment by Rohit-Satyam** [comment]
Hi @brentp . I don't know python much. Looking at the script, I see `chroms["total"] = True`. Is this you are talking about. 

If not can you please help me with exact command.

**Comment by clersdom** [comment]
Hi, were you able to resolve this? 
I would like to plot whole genome coverage for all the samples. The script creates by default individual plots for each chromosome and for each sample.
Thanks!

**Comment by brentp** [comment]
if you run as: `python scripts/plot-dist *.mosdepth.global.dist.txt`, then it will put all samples in the same html (plot) output. If that's not the issue,  can clarify the problem further?

**Comment by clersdom** [comment]
Hi @brentp, it has worked now, thanks!
The main issue is that all the `*.mosdepth.global.dist.txt` files need to be in the same directory. However, I still have not managed to plot the whole genome of all the samples in one unique plot. 
I wonder if the input file should be another as `mosdepth.global.dist.txt` contains the bases covered at a given coverage value but for each chromosome and not genome-wide?

**Comment by brentp** [comment]
> The main issue is that all the *.mosdepth.global.dist.txt files need to be in the same directory.

No, you can do, e.g. `python plot-dist.py /path/to/a/a.mosdepth.global.dist.txt /path/to/b/b.mosdepth.global.dist.txt /other/path/to/*.global.dist.txt`

> However, I still have not managed to plot the whole genome of all the samples in one unique plot.

My output has "Total" as the first plot in the html output. Can you share the HTML file?

**Comment by clersdom** [comment]
Right, I can see the total plot now. 
Thanks for your help @brentp

**Comment by clersdom** [comment]
Is there a way to fix the scale of the X axis somewhere in the script regardless of how the data looks like?
 I have made two groups and for some reason, the scale is different for each group (one shows coverage by 20, and the other by 10).

**Comment by zhaoruolan** [comment]
Hi,
I did get a dist.html file, but I don't know how to use this file to plot...I didn't see any plots during running the script either. Could you help? Many thanks.

**Comment by clersdom** [comment]
You need to copy the plot-dist.py file (scripts folder), and then run
`python path/plot-dist.py path/*global.dist.txt`

Do not run it like
`python /path/plot-dist.py /path/*global.dist.txt`

**Comment by brentp** [comment]
@zhaoruolan you can pull from latest github to get an updated script. For some genomes (e.g. GRCh38), there were so many chroms that ti was stalling.  I updated it this week to not plot HLA, random, and Un chromosomes.

@clersdom you can edit the script to set the range (https://plotly.com/javascript/axes/#setting-the-range-of-axes-manually) . So you would change the line that contains:
```
          xaxis: {title: 'Coverage'},
```
to something like:
```
        xaxis: {title: 'Coverage', range: [0, 30]},
```
