### ISSUE TITLE
Output mean and median in same run

### ISSUE THREAD

**Issue by shahmj** [brentp/mosdepth#96]
Hi,

I am running mosdepth as follows to get mean or median coverage:
`mosdepth -n --by 1000 <prefix> $bam -c $chrom -Q 20` or
`mosdepth -n --by 1000 <prefix> $bam -c $chrom -Q 20 -m`

Is there a way to get both values without having to run it twice?

Thanks,
Minita

**Comment by brentp** [comment]
hi, this isn't possible. you'll have to run it twice.

**Comment by heyudou** [comment]
Hello! I have encountered the same issue, the output of the 3 following commands are exactly the same:

--supposedly "median"
mosdepth -t 2 -n --use-median --by merged_CCDS_CodingExons.bed ${sample}_tumor $tumor
mosdepth -t 2 -n -m --by merged_CCDS_CodingExons.bed ${sample}_tumor $tumor

--supposedly "mean"
mosdepth -t 2 -n -by merged_CCDS_CodingExons.bed ${sample}_tumor $tumor


The headers in the output summary file says "mean" for all of them

example:

chrom	length	bases	mean	min	max
chr1	248956422	890358773	3.58	0	5628
chr1_region	3426109	228858960	66.80	0	5628
....

**Comment by brentp** [comment]
Hi, the summary files are not affected by --use-median. Only the --regions.bed.gz values are changed by this flag.

**Comment by heyudou** [comment]
I see, thanks for commenting.
Is there a way to get the overall median coverage in the regions covered by the bed file like it did with summary in mean?
